### ISSUE TITLE
Include occurrences of the old version number in the PR body

### ISSUE THREAD

**Issue by fthomas** [scala-steward-org/scala-steward#1006]
See https://github.com/scala/scala-xml/pull/359#issuecomment-533608205.

**Comment by fthomas** [comment]
I think it also makes sense to add a "tag" to the PR body if there were old version numbers that weren't updated. This could be used in Mergify rules to prevent automatic merges of PRs that contain this tag.

**Comment by DStranger** [comment]
Hi @fthomas!
I started working on this, but not sure what the best way of showing the files in the PR would be.
This is what I currently have (wording suggestions are also welcome!):
<img width="836" alt="Screenshot 2020-08-26 at 22 03 34" src="https://user-images.githubusercontent.com/1828565/91351670-f65de900-e7e8-11ea-81a0-c1d9dede1af1.png">

**Comment by mzuehlke** [comment]
That looks like a good addition to the PR message.
Even if it is a duplication I would include the old version number to make it very clear:

The following files still refer to the old version number (0.26.0).
