### ISSUE TITLE
Use GitHub to install Scala steward in a repo

### ISSUE THREAD

**Issue by fthomas** [scala-steward-org/scala-steward#102]
... instead of adding it to `repos.md`. I guess this requires making some kind of GitHub app for Scala steward. The only thing I'd need from GitHub would be a list of repos that have Scala steward "installed".

**Comment by fthomas** [comment]
I just tried creating a GitHub App but this is not possible without a webhook URL. :-/

**Comment by nafg** [comment]
What's stopping you from having one?

**Comment by fthomas** [comment]
It is mostly a lack of time for figuring out how to write a GH app.

**Comment by mzuehlke** [comment]
Hi @fthomas ,
I am trying to bring Scala Steward to our in-house Github Enterprise installation as an Github App and did some experimentation with the REST interface to find out the required changes. 
As Scala Steward is meant to be executed in a batch/cron style there is no need to implement a webhook at all. (Yes, you have to specify one, when configuring the app...)

Do you want to re-open this ticket or should I create a new one ?

Btw: thanks for this great peace of software.

**Comment by javierarrieta** [comment]
Any more advances into this @mzuehlke you can share? That would be greatly appreciated.

I am I guess in the same boat as our organisation is removing all bot accounts so we need to move to a github app

**Comment by fthomas** [comment]
I'm wondering if the GitHub Action (https://github.com/scala-steward-org/scala-steward-action) would be a viable alternative to a GitHub App? Probably not since the action also requires a bot (or user) account.

**Comment by xuwei-k** [comment]
Please reopen this issue 🙏 

I have created pull request. see https://github.com/scala-steward-org/scala-steward/pull/1766

> I just tried creating a GitHub App but this is not possible without a webhook URL. :-/

I think we don't need webhook if use [this list-repositories api](https://docs.github.com/en/free-pro-team@latest/rest/reference/apps#list-repositories-accessible-to-the-app-installation) in each scala-steward execution.

**Comment by nafg** [comment]
You can do this yourself with https://github.com/armanbilge/diy-steward
