### ISSUE TITLE
Compare url & release notes/changelog are restricted to {github,gitlab}.com

### ISSUE THREAD

**Issue by anilkumarmyla** [scala-steward-org/scala-steward#1088]
Current logic of generating compare url and release notes/changelog are restricted to either github.com or gitlab.com
```
if (repoUrl.startsWith("https://github.com/") || repoUrl.startsWith("https://gitlab.com/"))
```

Is it possible to configure/extend this, so that git enterprise urls (such as git.enterprise.company.com) can also be included in this?

**Comment by fthomas** [comment]
Sure. But `repoUrl` needs to determined first and it is currently coming from `CoursierAlg`. If the depedency is private, `CoursierAlg` needs to be made aware of the private artifact repository where it is hosted.

**Comment by anilkumarmyla** [comment]
Yes, coursier reads the repoUrl from the artifact, but if it’s other than github or gitlab, we don’t generate the compare link or point to release.

**Comment by exoego** [comment]
FYI:
I implemented this logic so because URLs other than github/gitlab are unlikely to have release notes/changelog, so I restrict to github/gitlab to avoid costy URL existence checking.

But recent PR https://github.com/fthomas/scala-steward/pull/1081 introduced cache for URL existence checking.
So I think now is reasonable to remove github/gitlab restriction, and add more URL patterns.

**Comment by anilkumarmyla** [comment]
> URLs other than github/gitlab are unlikely to have release notes/changelog

What I meant is that the url regex strictly checks for github.com/gitlab.com while in git enterprise setup these can be git.enterprise.company.com urls

**Comment by fthomas** [comment]
> But repoUrl needs to determined first and it is currently coming from CoursierAlg. If the depedency is private, CoursierAlg needs to be made aware of the private artifact repository where it is hosted.

This is not an issue anymore because `CoursierAlg` uses since https://github.com/scala-steward-org/scala-steward/pull/1226 the same artifact repositories as the build. I think the only functions that need to be changed to support this are the ones in the `vcs` package object.
