### ISSUE TITLE
Support for multi-build repos

### ISSUE THREAD

**Issue by ignasi35** [scala-steward-org/scala-steward#1158]
Projects with multiple builds (like [twirl](https://github.com/playframework/twirl), [play](https://github.com/playframework/playframework) or [lagom](https://github.com/lagom/lagom)) where there's a `ROOT/build.sbt` but also a `ROOT/docs/builds.sbt` (which may or may not refer to `ROOT/build.sbt`) are only partially supported.

The `ROOT/docs/*` project definition is a completely new project with its own `ROOT/docs/project/plugins.sbt` and its own set of dependencies, etc... One of the issues is that often we want to bump a dependency in all the builds of the repo in a single PR.

This is partially a duplicate of https://github.com/fthomas/scala-steward/issues/678 in that when solving https://github.com/fthomas/scala-steward/issues/678 it should be possible to list `playframework/twirl` and `playframework/twirl#ROOT/docs` (for example).

The ideal solution would be to upgrade (on a single PR) all projects in the repo at once. Users might need to specify all the builds in https://github.com/scala-steward-org/repos/blob/master/repos.md with some syntax like `playframework/twirl#{ROOT,ROOT/docs}`, for exaample.

**Comment by mzuehlke** [comment]
Superseded by #1875.
