### ISSUE TITLE
Nonexistent cats-effect version

### ISSUE THREAD

**Issue by REDNBLACK** [scala-steward-org/scala-steward#1184]
https://github.com/TinkoffCreditSystems/tofu/pull/78/files

Scala Steward changed catsEffect version from 2.0.0 to 2.1.0

**Comment by rintcius** [comment]
Similar issue here:
https://github.com/slamdata/quasar/pull/4434/files for jawn
and https://github.com/slamdata/quasar/pull/4458/files
