### ISSUE TITLE
Add scalatestplus.scalacheck for ScalaTest 3.0 -> 3.1 migration if ScalaCheck is present

### ISSUE THREAD

**Issue by REDNBLACK** [scala-steward-org/scala-steward#1187]
As mentioned in ScalaTest 3.1 release notes http://www.scalatest.org/release_notes/3.1.0:

> The major new feature of ScalaTest 3.1.0 is modularity. Anything involving third party integrations has been moved to an org.scalatestplus package. For example, ScalaCheck integration has been moved to the org.scalatestplus.scalacheck package

For this reason scalafix migration PR failed, as can be seen here: https://github.com/TinkoffCreditSystems/typed-schema/pull/193

The only missing part was `"org.scalatestplus" %% "scalatestplus-scalacheck"` dependency

**Comment by mwz** [comment]
Personally, it took me a little while to track down where the `scalacheck` and `mockito` dependencies are coming from in `3.1.0`, so if this could be automated that would be amazing, although it's probably already a little bit too late now to think about it...

I can't remember I've seen similar modularisation changes done recently to any other libraries out there, so I'm not sure how useful that feature would be in the future beyond that particular scalatest migration if this was to be implemented in a more generic way.

There are even more "modular" changes coming to scalatest in `3.2.0`, but those are around extracting internal features to separate modules, like the type of the test suite you use e.g. `scalatest-funsuite` or `scalatest-flatspec` or the type of matchers e.g. `scalatest-shouldmatchers` or `scalatest-mustmatchers`, so I'm not sure if Scala Steward will be able to help with those.

**Comment by manuelcueto** [comment]
Apparently the artifact name is now 
`"org.scalatestplus" %% "scalacheck-1-14" % "3.1.0.0"` 🤦‍♂ 
https://github.com/scalatest/scalatestplus-scalacheck/blob/master/build.sbt

**Comment by exoego** [comment]
I think it is 
- A bit tricky to implement "add missing dependency" in Scala Steward. It is a bit difficult to determine where `"org.scalatestplus" %% "scalacheck-1-14" % "3.1.0.0"` should be inserted in build files.
- 2 years passed from ScalaTest 3.1 release, and I assume most of ScalaTest users are already performed this migration by themselves.
- Going modular is less common, so this feature seems less helpful for other dependencies

So, I think this feature has a very little value compared to its effort and complexness.
Let me close as wontfix 🙇
