### ISSUE TITLE
Next version selection doesn't work for specific versions with hashes

### ISSUE THREAD

**Issue by xicmiah** [scala-steward-org/scala-steward#1260]
Versions with commit hash containing `b` are not considered at all.

Here's a sample, modified from `VersionTest`'s `"selectNext, table 2"`:
```scala
val current = Version("1.2.0+9-4a769501")
val next = Version("1.2.0+17-7ef9b061")
current.selectNext(List(next)) shouldBe Some(next)
```

It seems that `b061` part gets parsed as `BETA` pre-release version, triggering `Do not select pre-release versions of a different series` case.

A quick workaround could be removing `b` clause in [Version.scala#L119](https://github.com/fthomas/scala-steward/blob/master/modules/core/src/main/scala/org/scalasteward/core/data/Version.scala#L119)

**Comment by manuelcueto** [comment]
the b clause was added as some beta versions are marked with `b` addressing #1136

I can take a look at this.

**Comment by jan-pieter** [comment]
I am running into the same issue. Our versioning scheme for libraries is `1.0.0-<dateTtime>-<commitHash>'. Whenever the commit hash contains a `b` scala steward ignores the update. I think it would be nice to be able to configure this behaviour in the repository-specific configuration file.

**Comment by fthomas** [comment]
I would prefer fixing `selectNext` instead of adding a config flag for this. We should be able to detect if a version ends with a commit hash and ignore `b` as pre-release identifier there.

**Comment by fthomas** [comment]
I opened #1549 to address this issue.
