### ISSUE TITLE
Add release notes/changelog/version diff for dependencies in private GitHub repos

### ISSUE THREAD

**Issue by MPV** [scala-steward-org/scala-steward#1468]
These nice features don't work for dependencies whose git repos are private (thus need auth):
- Release Notes
- Changelog
- Version Diff

This is probably because the http client used for those doesn't seem to use the github token:

https://github.com/fthomas/scala-steward/blob/master/modules/core/src/main/scala/org/scalasteward/core/util/HttpExistenceClient.scala

**Comment by fthomas** [comment]
`HttpExistenceClient` has been renamed to [`UrlChecker`](https://github.com/scala-steward-org/scala-steward/blob/0315d316f753696948befa2db4aff03f52e1c2d6/modules/core/src/main/scala/org/scalasteward/core/util/UrlChecker.scala). I think the `Client` used by `UrlChecker` needs do authenticated calls for anything that goes to `VCSCfg#apiHost`. I once tried this in this old branch (https://github.com/scala-steward-org/scala-steward/compare/topic/VCSClient) but then ran out of steam.

**Comment by fthomas** [comment]
There is now a PR at #2920 that fixes this if someone wants to give it a try.

**Comment by laughedelic** [comment]
Great news! Thanks!

Can I try this version with the [scala-steward-action](https://github.com/scala-steward-org/scala-steward-action)?

**Comment by fthomas** [comment]
Yes, just set the `scala-steward-version` option of the action to `0.20.0-61-1f0282a6-SNAPSHOT` for example. Available snapshot versions are here: https://oss.sonatype.org/content/repositories/snapshots/org/scala-steward/scala-steward-core_2.13/

**Comment by lenguyenthanh** [comment]
This currently doesn't work for private github repositories. because normal url like `https://`github.com/org/private-repository` will not accept any token. So both basic auth and jwt token don't work.

I'm not sure this is a regression or it has never worked 🤔 

Can anyone confirm?

**Comment by laughedelic** [comment]
In my experience it never worked
