### ISSUE TITLE
Move this repository to the scala-steward-org organization

### ISSUE THREAD

**Issue by fthomas** [scala-steward-org/scala-steward#1486]
I think it is past due that this repository is moved to the [scala-steward-org](https://github.com/scala-steward-org) organization. This project has grown from a personal toy project to a (in my opinion) well established tool in the Scala ecosystem with contributions of over 50 different people. Development and maintenance of Scala Steward has been a collaborative effort for quite some time now and this should at least be reflected in the location of the main Scala Steward repository. I'd also like to invite more people to be maintainer of this repo (with merging rights) once it is moved.

I'm also opening this issue to collect any things that needs to be done before and after moving the repo to have a smooth transition.

**Comment by dwijnand** [comment]
Done

**Comment by fthomas** [comment]
Yes, this is done. The repo has been moved, @mzuehlke has now merging rights, and other apps and services are now pointing here too. The only thing that is still tied to a personal account is the location for the Docker images (https://hub.docker.com/r/fthomas/scala-steward). But maybe we can use GitHub Packages for Docker images in the future.
