### ISSUE TITLE
a feature to update copyright years in headers

### ISSUE THREAD

**Issue by erikerlandson** [scala-steward-org/scala-steward#1507]
a copyright statement is common in code header comments.  It would be a nice labor-saver for scala steward to generate a PR that updates them every year.

"Copyright 2017-2019" --> "Copyright 2017-2020"

**Comment by fthomas** [comment]
I'm not yet decided if this is a good fit for Scala Steward but wanted to mention that https://github.com/sbt/sbt-header can update them via the `headerCreate` task.

**Comment by erikerlandson** [comment]
> mention that https://github.com/sbt/sbt-header can update them via the headerCreate task. 

thanks, didn't know about that!

**Comment by fthomas** [comment]
I now think that such feature would not be a good fit for Scala Steward. I'd like Scala Steward's focus for now to be on updating dependencies and there is still plenty of work to do to get better at this. Updating copyright years is very different from the things Scala Steward currently does.
