### ISSUE TITLE
Support for gitea servers.

### ISSUE THREAD

**Issue by jan0sch** [scala-steward-org/scala-steward#1536]
It would be great to have support for the [gitea](https://gitea.io) git hosting server.

- https://docs.gitea.io/en-us/api-usage/
- https://try.gitea.io/api/swagger

**Comment by fthomas** [comment]
Since we already support GitHub, GitLab, Bitbucket and Bitbucket Server, this shouldn't be too hard to add.

**Comment by fthomas** [comment]
WIP PR for Gitea support: https://github.com/scala-steward-org/scala-steward/pull/2758
