### ISSUE TITLE
[Question] - Best way to include a dependency for steward to manage that is only used via `BuildInfo`

### ISSUE THREAD

**Issue by ckipp01** [scala-steward-org/scala-steward#1555]
Hello! Just a quick question about the recommended way to include a version of a dependency that doesn't have the full identifier, but is used in your code base. You can see a real world example of what I'll explain below [here in metals](https://github.com/scalameta/metals/pull/1954/files).

In metals we've had this conversation a couple times, but never hit on the best solution. But for example, if we want to have a version of a tool, mill for example, but we never actually have the full identifier for mill anywhere, but want to keep track of the version to check it when we connect to it, what would be the recommended way to do that. Currently we include it in our `build.sbt` because we want to be notified up the new versions

```scala
// build.sbt
val mill = 0.8.0
```

Then we are giving it to build info and in our codebase accessing it to potentially show it in a message to the user. In order to get this captured by Scala Steward we currently just include a dependency in our test suite even though we don't use it like:

```scala
// The dependencies listed below are only listed so Scala Steward
// Not actually used in tests.
// will pick them up and update them. They aren't actually used.
"com.lihaoyi" % "mill-contrib-testng" % V.mill intransitive ()
```

Is there a better way you'd recommend to do this that we can point scalasteward to an artifact rather than including a random one just to get it to trigger? Any advice would be greatly appreciated. I looked around a bit and wasn't able to get a good answer to this, so my apologies if I missed something.

Thanks!

**Comment by fthomas** [comment]
For these situations I've been recommending adding a dummy sbt subproject that depends on the libraries you want to receive updates for, is aggregated in the root project but skipped for publishing. This works great for example for g8 templates or sbt plugins that provide SettingKeys for common dependencies. Using `intransitive()` to prevent fetching these dependencies if they are not needed seems like recommendation, too.

**Comment by ckipp01** [comment]
Sounds good. I appreciate the input!
