### ISSUE TITLE
Filter out unwanted versions by regex

### ISSUE THREAD

**Issue by ryanb93** [scala-steward-org/scala-steward#1560]
Sometimes a library (usually internal company libraries) will publish snapshots, branch builds, or some other prefix/suffix to indicate a non-release build. For example something like:

```
1.0.1 to 1.0.2.feature/test
1.0.1 to 1.0.2.dev1234
```

Currently `scala-steward` will create a PR using this later version which is not ideal. It would be good to provide users of the service with a way of configuring dependencies to ignore these sort of versions. There is [already support](https://github.com/scala-steward-org/scala-steward/blob/master/modules/core/src/main/scala/org/scalasteward/core/data/Version.scala#L127) for ignoring `SNAPSHOT`, `ALPHA`, `BETA`, `MILESTONE` and `RC` - this could be extended to provide a negative order for a user defined list of string values, configured via `.scala-steward.conf`. Or it might be something that could be added to individual dependencies rather than a global setting.

**Comment by fthomas** [comment]
There is already the `updates.ignore` setting in `.scala-steward.conf` which can be used to ignore updates that match a given pattern. It currently requires a groupId and can only match a prefix, or suffix of the version but maybe we can tweak that so that the groupId is optional and versions match if they contain a given string. I think I would prefer that to a new way to ignore updates.

**Comment by fthomas** [comment]
I propose to fix this by adding a new `contains: Option[String]` field to [`VersionPattern`](https://github.com/scala-steward-org/scala-steward/blob/209092f3726858ca5e3b1a50612fad0a6eaa9ccd/modules/core/src/main/scala/org/scalasteward/core/repoconfig/VersionPattern.scala) that matches substrings in the version. So for example, to prevent updates to versions like `1.0.2.feature/test`,  one would add this to `.scala-steward.conf`:
```
updates.ignore = [ { groupId = "org.example", version = { contains = "feature" } } ]
```
This entry would work for all dependencies with the `org.example` groupId. Would this work for you @ryanb93?

**Comment by ryanb93** [comment]
> I propose to fix this by adding a new `contains: Option[String]` field to [`VersionPattern`](https://github.com/scala-steward-org/scala-steward/blob/209092f3726858ca5e3b1a50612fad0a6eaa9ccd/modules/core/src/main/scala/org/scalasteward/core/repoconfig/VersionPattern.scala) that matches substrings in the version. So for example, to prevent updates to versions like `1.0.2.feature/test`,  one would add this to `.scala-steward.conf`:
> 
> ```
> 
> updates.ignore = [ { groupId = "org.example", version = { contains = "feature" } } ]
> 
> ```
> 
> This entry would work for all dependencies with the `org.example` groupId. Would this work for you @ryanb93?


That would work nicely for my use case.

**Comment by mzuehlke** [comment]
What about the more generic version to give a `regex` instead of `contains` ?

**Comment by fthomas** [comment]
I don't want to support regular expressions in `.scala-steward.conf` because of the possibility of DoS attacks: https://owasp.org/www-community/attacks/Regular_expression_Denial_of_Service_-_ReDoS
