### ISSUE TITLE
Running scalafmt automatically can hide more significant changes

### ISSUE THREAD

**Issue by jrudolph** [scala-steward-org/scala-steward#1569]
It seems in some cases scala-steward runs scalafmt (after scalafix?) which introduces insignificant changes at other places in the code base.

E.g. here: https://github.com/akka/akka-minion/pull/174/files

This makes scala-steward's PRs more difficult to review.

Not sure when this would actually be useful but it shouldn't probably enabled by default.

**Comment by jrudolph** [comment]
Just saw https://twitter.com/schrepfler/status/1291442470979600385, so the formatting changes were unintended from scala-steward's side. From our side as well, so I'll have a look how it would be caused by scalafix itself.

**Comment by jrudolph** [comment]
As observed in https://github.com/schrepfler/artemis/pull/106, it seems to have been pure coincidence that there was a scalafmt update just a bit before the akka http update. When scala-steward then ran scalafix for akka-http and the formatting changes were not yet in master of the project, it seems that running scalafix triggered an automatic scalafmt update.

So, in some way it's related to #1056. 

One thing that is left for this ticket might be to set `scalafmtOnCompile := false` before running scalafix automatically.

**Comment by fthomas** [comment]
I would prefer not modifying the `scalafmtOnCompile` setting that is only available if the build uses a certain plugin. My fear is that modifying this setting would be brittle or could lead to other errors.

I understand that the formatting changes are not desirable but with `scalafmtOnCompile := true` and not properly formatted source code you exactly get what you were asking for. :-) I would advise to check the formatting in CI builds and not merging Scalafmt updates that would lead to formatting changes without actually updating the formatting or not using `scalafmtOnCompile` at all.

**Comment by fthomas** [comment]
Now that Scala Steward reformats the code on scalafmt updates (#1673), situations like the one described in https://github.com/scala-steward-org/scala-steward/issues/1569#issuecomment-671295755 are less likely. Since I don't want to touch the `scalafmtOnCompile` setting, I can't think of much else we could do about this issue.
