### ISSUE TITLE
How to activate scala-steward for a repo deleted and re-created?

### ISSUE THREAD

**Issue by 9rb** [scala-steward-org/scala-steward#1591]
I had added 9rb/rchain to the .md file to receive scala-steward alerts and it worked. I had to delete the repo due to problems on my end. I recreated the repo. How do I now tell scala-steward to start sending updates? I have not been receiving them. I'm not sure what scala-steward uses other than the path to identify and manage the state of the repo.  

I could probably delete my repo from the steward's .md file and add it again - but was not sure if that's the correct process or that would be annoying to the PR approvers. Thanks in advance

**Comment by fthomas** [comment]
I see https://github.com/9rb/rchain/pull/11 which indicates to me that @scala-steward started sending updates to your repo again. Can we close this issue?

**Comment by 9rb** [comment]
yes, thanks
