### ISSUE TITLE
Another Process update ... no files were changed

### ISSUE THREAD

**Issue by tyrcho** [scala-steward-org/scala-steward#1600]
This is quite similar to #1586 with a slightly different setup

We defined versions in a `project/Dependencies.scala` file like this
```scala
object ApachePoi4 {
    final val version = "4.0.1"

    final val core  = "org.apache.poi" % "poi"       % version
    final val ooxml = "org.apache.poi" % "poi-ooxml" % version

    final val all = Seq(core, ooxml)
  }

  object ScalaDistances {
    final val version = "1.0.1"

    final lazy val core     = "com.colisweb" %% "scala-distances-core"            % version
    final lazy val provider = "com.colisweb" %% "scala-distances-provider-google" % version
    final lazy val cache    = "com.colisweb" %% "scala-distances-cache-redis"     % version
    final lazy val noCache  = "com.colisweb" %% "scala-distances-cache-noCache"   % version

    final lazy val all = Seq(core, provider, cache, noCache)
  }
```

And here is the [log file](https://gitlab.com/colisweb-open-source/scala-steward/-/jobs/717262871#L762)

```
2020-09-03 05:21:10,401 INFO  Process update org.apache.poi:{poi, poi-ooxml} : 4.0.1 -> 4.1.2
2020-09-03 05:21:10,555 INFO  Trying heuristic 'moduleId'
2020-09-03 05:21:10,561 INFO  Trying heuristic 'strict'
2020-09-03 05:21:10,566 INFO  Trying heuristic 'original'
2020-09-03 05:21:10,574 INFO  Trying heuristic 'relaxed'
2020-09-03 05:21:10,579 INFO  Trying heuristic 'sliding'
2020-09-03 05:21:10,585 INFO  Trying heuristic 'completeGroupId'
2020-09-03 05:21:10,589 INFO  Trying heuristic 'groupId'
2020-09-03 05:21:10,595 INFO  Trying heuristic 'specific'
2020-09-03 05:21:10,599 WARN  No files were changed
```

**Comment by tyrcho** [comment]
Is this possible to support and update with scala-steward ?

If no, I think we should document more explicitly which syntaxes are supported. We relied a lot on scala-steward in the past months to update our dependencies ... and I've discovered that all our projects with this structure were not updated at all !

**Comment by tyrcho** [comment]
I don't see how scala-steward could support arbitrary value name for updating versions without major rework (like with dotty tools which "understand" the source code).

However, I would suggest that steward creates a PR/MR with some comment to suggest that the update is fixed manually.

The current behaviour is the libraries are not updated, and I only discovered that by digging into scala-steward logs. It means that projects which rely on steward to get updates only have parts of their libraries updated and are not notified at all.

What about adding a line in build.sbt like
```scala
// an update was found for org.apache.poi:{poi, poi-ooxml} : 4.0.1 -> 4.1.2
// the update could not be applied automatically because scala-steward could not determine which line to change
// see this page (TODO link to doc) to see how you should name your versions in a supported way
```

**Comment by fthomas** [comment]
> Is this possible to support and update with scala-steward ?

Yes, I think a new heuristic I described in https://github.com/scala-steward-org/scala-steward/issues/1534#issuecomment-658000263 could work in these cases.

Another idea would be to take the preceding line into account when the version number is on a line that only contains unspecific words like `val`, `def`, `version`, `final`, `lazy`, etc.

**Comment by tyrcho** [comment]
yes, that would probably do the job.

I'll let you decide if you close this issue, and I'll create a separate one for my last proposal => #1606

**Comment by exoego** [comment]
Let me close as duplicate since https://github.com/scala-steward-org/scala-steward/issues/1534#issuecomment-658000263 covers and #1606 is opened.
