### ISSUE TITLE
[Question] - Resolving sbt plugins in private nexus

### ISSUE THREAD

**Issue by ckipp01** [scala-steward-org/scala-steward#1628]
I've been stuck on this for a while so I figured it's time to see if I'm maybe just completely missing something. We've been using this at work and it's working fantastically for our 100+ repos. However, the only thing that is tripping up a bit is that we publish an internal sbt plugin, and it's published maven style with `publishMavenStyle := true` because of internal Nexus rules. Everything works as expected when we need to resolve the plugin etc, but since it's published maven style as a plugin there is no `maven-metadata.xml`. So even though the plugin is picked up as a dependency, I do see a `maybeError` message in the `versions.json` file notifying me that there is no `maven-metadata.xml`, meaning there is no versions listed in the versions array.

Is there any way around this or anything extra we can give to Steward to help pick up the published versions of the internal plugin that is published this way, or is it fully reliant on the metadata file being there? Reading around, I'm assuming we aren't the only ones that are publishing internal plugins maven style. I'm curious if anyone has hit on this before and has a solution that I'm not thinking of.

**Comment by fthomas** [comment]
Is your sbt plugin published with not only the Scala binary version as suffix but also with the sbt binary version like sbt-scalafmt for example (https://repo1.maven.org/maven2/org/scalameta/sbt-scalafmt_2.12_1.0/). AFAIK Coursier appends both binary versions to the artifactId and then uses the directory listing as above to get all available versions. Does your Nexus allow directory listings?

As you can see from the listing above, there is also no `maven-metadata.xml` for sbt-scalafmt but Scala Steward is able to update that plugin regardless.

**Comment by ckipp01** [comment]
> Does your Nexus allow directory listings?

Maybe that's what I'm missing. For example in our mirror I see sbt-scalafmt listed like so:

<img width="204" alt="Screenshot 2020-09-29 at 21 48 34" src="https://user-images.githubusercontent.com/13974112/94608580-e03ac100-029d-11eb-8b70-21ddd8e1e38d.png">

But then I see our internan plugin with the same naming convention, but I notice the icon is different 🤔 
<img width="284" alt="Screenshot 2020-09-29 at 21 49 15" src="https://user-images.githubusercontent.com/13974112/94608617-efba0a00-029d-11eb-9f23-bc9db59e2c42.png">

Which possibly points to the issue of there not being any sort of listing. I'll investigate that further. Thanks! If you don't mind I'll keep this open for a bit while I investigate, and if I don't find a solution, I'll close in a couple days or close when I find the actual fix.

**Comment by ckipp01** [comment]
So after a little digging, this seems to for sure be the problem. If I'm understanding how coursier is getting the versions her when no `maven-metadata.xml` is present it's relying on the artifact index / directory listing. In our corporate mirror that happens to work fine and be here:

```
https://nexus-redacted.com/repository/maven-public/org/scalameta/sbt-scalafmt_2.12_1.0
```
However, for our internally hosting plugins there seems to be no listing as the same will 404
```
https://nexus-redacted.com/repository/redacted-releases/redacted/redacted/sbt-redacted_2.12_1.0
```
When trying to figure out if there is a way to enable it I came across [this help article](https://community.sonatype.com/t/nexus-3-html-view-and-index/2841) which seems to imply that as of Sonatype 3 this index listing is not longer possible (at least not at the same path). If that's the case I'm assuming that coursier isn't programmed to look at this new path for the index listing. I feel like I can't be the only one that has come across this. I have to be missing something. Any ideas?

**Comment by fthomas** [comment]
Scala Steward relies on Coursier for getting available versions of artifacts. The only thing we can do here is to tweak how we use Coursier's API, but I doubt that helps in this case. So I assume that Coursier's Versions API need to be adapted to Nexus 3.

**Comment by ckipp01** [comment]
> Scala Steward relies on Coursier for getting available versions of artifacts. The only thing we can do here is to tweak how we use Coursier's API, but I doubt that helps in this case. So I assume that Coursier's Versions API need to be adapted to Nexus 3.

That's sort of what I assumed. Thanks @fthomas 👍 I'll close and follow-up in Coursier.
