### ISSUE TITLE
[Feature request] Add PR superseding support?

### ISSUE THREAD

**Issue by hepin1989** [scala-steward-org/scala-steward#1670]
![image](https://user-images.githubusercontent.com/501740/96334026-26ff2800-10a0-11eb-80c6-8583a3a91157.png)
I think the PR of `Update scalafmt-core to 2.7.3` can be suspended by the PR of `Update scalafmt-core to 2.7.4`
refs: https://github.com/akka/akka/pulls

**Comment by hepin1989** [comment]
![image](https://user-images.githubusercontent.com/501740/96337158-79980e80-10b7-11eb-8f98-c02b6887a0ce.png)

**Comment by exoego** [comment]
I guess this is realized in #1667?

**Comment by fthomas** [comment]
Sounds like #1667 to me, too. @hepin1989, if you had something else in mind, please comment and reopen.
