### ISSUE TITLE
Enhancement: Understanding sbt-github-actions

### ISSUE THREAD

**Issue by djspiewak** [scala-steward-org/scala-steward#1745]
When upgrading sbt-github-actions, you almost always need to re-run `sbt githubWorkflowGenerate`, otherwise the workflow will be out of date. Technically, this is probably also a good idea when upgrading *anything* build-related in a project using sbt-github-actions, since plugins could (for example) set `crossScalaVersions`, which in turn dictates the contents of the workflow.

Without this feature, scala-steward updates of sbt-github-actions dependencies are mostly useless. *With* this feature, updates of this plugin are almost magic because your CI build immediately begins evolving with the same ease as your dependencies.

**Comment by fthomas** [comment]
Agreed, running `sbt githubWorkflowGenerate` after updating sbt-github-actions would be useful. We're already doing something similar for scalafmt where we run it after bumping the version in `.scalafmt.conf`.

**Comment by fthomas** [comment]
A first draft for this feature is at #1751. An example PR for sbt-github-actions is at https://github.com/scala-steward-org/test-repo-2/pull/10.

**Comment by djspiewak** [comment]
That is very very cool
