### ISSUE TITLE
Incorrect update of  "commons-codec" % "commons-codec" 

### ISSUE THREAD

**Issue by froth** [scala-steward-org/scala-steward#1753]
Scala steward tried to update

`"commons-codec" % "commons-codec" % "1.15"`

to 

`"commons-codec" % "commons-codec" % "20041127.091804"`

which is some crazy old snapshot-like version I think.

This happened some hours ago on our private gitlab repo. 

I see that the version number could confuse the steward as the old one is higher indeed. However we have this dependency in our projects since we started using scala steward and it did not try to update it until now.

(same for `commons-io`)

**Comment by fthomas** [comment]
My public instance created such PRs too, https://github.com/amorvincitomnia/thehand/pull/142 and https://github.com/broadinstitute/cromwell/pull/6061 for example.

The version comparison code in Scala Steward hasn't been touched recently, so I don't know for sure why they have been created now. I looked at Scala Steward's version cache and noticed that they are not on Maven Central and are only available on JCenter / JFrog:
```sh
workspace/store/versions/v2$ grep -R 20041127 *
https/jcenter.bintray.com/commons-codec/commons-codec/versions.json:    "20041127.091804"
https/broadinstitute.jfrog.io/broadinstitute/libs-release/commons-codec/commons-codec/versions.json:    "20041127.091804"
https/broadinstitute.jfrog.io/broadinstitute/libs-snapshot/commons-codec/commons-codec/versions.json:    "20041127.091804"

workspace/store/versions/v2$ grep -R 20030203.000550 *
https/jcenter.bintray.com/commons-io/commons-io/versions.json:    "20030203.000550"
https/broadinstitute.jfrog.io/broadinstitute/libs-release/commons-io/commons-io/versions.json:    "20030203.000550"
https/broadinstitute.jfrog.io/broadinstitute/libs-snapshot/commons-io/commons-io/versions.json:    "20030203.000550"
```
Maybe these versions have been added to JCenter only recently? I don't know.

We could prevent Scala Steward from creating PRs for these versions in the future by adding them to [`FilterAlg.badVersions`](https://github.com/scala-steward-org/scala-steward/blob/95f85a7b98a1cc21e6a2c7ec147ba90641e2d272/modules/core/src/main/scala/org/scalasteward/core/update/FilterAlg.scala#L121-L170).
