### ISSUE TITLE
bot confused after change of github organization

### ISSUE THREAD

**Issue by yanns** [scala-steward-org/scala-steward#1782]
by having a look at https://github.com/sangria-graphql/sangria/pull/530/files, it seems that the bot still has files from the [temporary fork](https://github.com/sangria-graphql-org/sangria) as it contains the [readme notice](https://github.com/sangria-graphql-org/sangria/commit/dad2c503d0ae77f7fec459a225e0a5de72ccd0ed).

This notice does not appear in the [README in the official organization](https://github.com/sangria-graphql/sangria/blob/master/README.md).

**Comment by fthomas** [comment]
https://github.com/scala/scala3-example-project/pull/40 is another instance of the same problem. I need to delete all of Scala Steward's sangria-graphql forks to fix this.

**Comment by yanns** [comment]
> [scala/scala3-example-project#40](https://github.com/scala/scala3-example-project/pull/40) is another instance of the same problem. I need to delete all of Scala Steward's sangria-graphql forks to fix this.

Sorry for that. I did not want to put more work on your shoulders...

**Comment by fthomas** [comment]
I've now deleted all of @scala-steward's sangria-graphql-org forks. It should soon fork the repos again from the sangria-graphql organization so that PRs do not contain changes from sangria-graphql-org repos anymore.

**Comment by yanns** [comment]
Thanks a lot! ❤️
