### ISSUE TITLE
Am I confused or is `updates.limit` not working?

### ISSUE THREAD

**Issue by aednichols** [scala-steward-org/scala-steward#1788]
Our public repo is [configured](https://github.com/broadinstitute/cromwell/blob/develop/.scala-steward.conf#L54) with
```
updates.limit = 5
```
but we currently have [47 open PRs from Scala Steward](https://github.com/broadinstitute/cromwell/pulls/scala-steward).

I think the expected result should be only 5 PRs open; is that correct?

Thank you for the great tool!

**Comment by fthomas** [comment]
Scala Steward does not run continuously but is run periodically (via cron). Each time it works on a repository it only creates up to `update.limit` new PRs. So in your case, it is allowed to create 5 new PRs every few hours. We don't have an option to limit the total number of open Scala Steward PRs per repository.
Maybe it would be clearer if this option is called `limitPerRun` or something similar. I guess the documentation could be clarified too. Suggestions how to improve the name of that option or the documentation would be very welcome!

**Comment by aednichols** [comment]
Thanks that explains things very nicely. I will consider updating the docs but will close the issue for now.
