### ISSUE TITLE
Feature idea: don't close superseded PRs if they were manually updated

### ISSUE THREAD

**Issue by kubukoz** [scala-steward-org/scala-steward#1871]
E.g. in https://github.com/pitgull/pitgull/pull/102 I manually pushed a change to fix the compilation after the update. The superseding PR obviously didn't have that, so I'll need to repeat that work.

**Comment by fthomas** [comment]
I think that is a good idea and it should be easy to implement. We could just look at the branch of the old update and check that it only contains commits of one author before closing the PR. The comment that the old PR has been superseded by a newer one is IMO still useful and should be posted.

**Comment by kubukoz** [comment]
Agreed!
