### ISSUE TITLE
Release 0.9.0

### ISSUE THREAD

**Issue by fthomas** [scala-steward-org/scala-steward#1886]
I think it is time for a new release. If nothing serious comes up in the next few days, I'm going to release version 0.9.0.

**Comment by barryoneill** [comment]
@fthomas Nice!  Thanks for the work - Any chance of it appearing on docker soon?

**Comment by fthomas** [comment]
It is released now.

**Comment by barryoneill** [comment]
I see it now, thank you again!

**Comment by mzuehlke** [comment]
Github release: https://github.com/scala-steward-org/scala-steward/releases/tag/v0.9.0
Docker image: [fthomas/scala-steward:0.9.0](https://hub.docker.com/layers/fthomas/scala-steward/0.9.0/images/sha256-85498f32deae8468855f25cf613a30749b5b9fbd517246a4f6a859d7f4237259?context=explore)
