### ISSUE TITLE
0.9.0 missing on maven central

### ISSUE THREAD

**Issue by xuwei-k** [scala-steward-org/scala-steward#1903]
🤔 
https://repo1.maven.org/maven2/org/scala-steward/scala-steward-core_2.13/

![maven-central](https://user-images.githubusercontent.com/389787/105657458-c20d6680-5f07-11eb-8a76-6b9a81234c2e.png)

**Comment by fthomas** [comment]
It is on https://oss.sonatype.org/service/local/repositories/releases/content/org/scala-steward/scala-steward-core_2.13/0.9.0/. I've no idea why it hasn't been synced to Maven Central yet.

**Comment by fthomas** [comment]
I've published 0.9.1 and that is already on Maven Central.
