### ISSUE TITLE
Semantics of pin configuration

### ISSUE THREAD

**Issue by ches** [scala-steward-org/scala-steward#1907]
Hi team, this is probably a question more than a bug report initially…

I have this repository configuration:

```hocon
updates.pin [
  # Newer major versions break with internal Hadoop platform lib versions
  { groupId = "org.datanucleus", artifactId = "datanucleus-accessplatform-jdo-rdbms", version = "3.3." }
]
```

The project currently uses version 3.3.8 of this dependency. I expect this `updates.pin` config to mean:

  - Steward will propose an update to 3.3.9+
  - Steward will not propose updates >= 3.4

Yet in actuality, Steward proposed an update to 5.2.7. Is that expected? If so, I must misunderstand the semantics of `updates.pin`.

We had some back-and-forth conjecturing interpretations of the doc lines:

```
# The dependencies which match the given version pattern are updated.
# Dependencies that are not listed will be updated.
```

One interpretation is that the first line applies to the _current_ version of a dependency in the project. This doesn't make sense to me, "if my current version of datanucleus matches `3.3.`, propose any update including major versions" does not seem useful, I wouldn't need any `pin` configuration to get that behavior.

In fuzzy human terms, my expectation for pin semantics might be worded like this to disambiguate, arguably:

> Dependency updates which match the given version pattern will be proposed.

If my understanding is correct and the update to 5.2.7 above is not expected, I'll dig into minimizing a reproduction and grokking test cases. We have some particulars of our internal Steward instance deployment to rule out. Just wanted to first make sure I'm not fundamentally off base.

**Comment by fthomas** [comment]
I agree with your understanding of the `updates.pin` semantics. Scala Steward should only propose updates if the new version starts with `3.3.`.

Btw, the `=` or `:` is missing after `updates.pin` in
```
updates.pin [
  # Newer major versions break with internal Hadoop platform lib versions
  { groupId = "org.datanucleus", artifactId = "datanucleus-accessplatform-jdo-rdbms", version = "3.3." }
]
```
Could this be the culprit?

**Comment by ches** [comment]
> Btw, the `=` or `:` is missing after `updates.pin`

Whoops, that's a legitimate typo from the real usage and not an omission in the issue report 🤦🏼 

Pretty safe to assume that is the culprit, will re-open if there are still any surprises in pinning behavior… Thanks for the extra set of rubber ducky eyes 😅
