### ISSUE TITLE
Feature suggestion: automatically update README with newest version

### ISSUE THREAD

**Issue by soronpo** [scala-steward-org/scala-steward#1908]
In many repositories in the README we have usage instructions (E.g., the line that appears in SBT). Unfortunately, those instructions are usually not up-to-date with newest published version. It will be nice if Scala Steward can take care of that too.

**Comment by fthomas** [comment]
This should be already possible. I think it requires adding the README to [`updates.fileExtensions`](https://github.com/scala-steward-org/scala-steward/blob/master/docs/repo-specific-configuration.md) and adding the library to the `libraryDependencies` of the project. The definition in the sbt file should be the same as in the README to ensure that Scala Steward updates both versions.

**Comment by soronpo** [comment]
But the library cannot depend on itself. Only the README of the library should. Would it work with just adding the `.md` in `fileExtensions`?

**Comment by fthomas** [comment]
> But the library cannot depend on itself.

You could add a dummy sbt subproject that depends on the library and is only aggregated by the root project but not used anywhere else. I think that should work.

**Comment by soronpo** [comment]
I see. Sounds too hacky to me. Where should I investigate codewise to create a special case for Steward to handle this?

**Comment by fthomas** [comment]
I'd prefer to not add a special case to Scala Steward for this. Its purpose is to update a project's dependencies and not its documentation. I think there is also a much more elegant solution for this problem: use a tool like [mdoc](https://github.com/scalameta/mdoc) to generate the README with the current version from the build. This way updating the version in the README could be part of the release process. Another advantage of using mdoc is that code examples - which are also often part of a README - could be machine-checked. A project where I'm doing all this is https://github.com/fthomas/fs2-cron.
