### ISSUE TITLE
Issue with crossScalaVersions update

### ISSUE THREAD

**Issue by matsluni** [scala-steward-org/scala-steward#1979]
Hi,

thanks for the awesome scala-steward! :trophy: 

I just noticed an updated for the scala library in my repo. The PR wants to update the wrong scala version in `crossScalaVersions`. See the incorrect behavior in this PR: https://github.com/matsluni/aws-spi-akka-http/pull/99/files

There is another PR in the same repo, which updates the correct `crossScalaVersions` here: https://github.com/matsluni/aws-spi-akka-http/pull/100

Let me know, if I can help you investigating this further.

PS: I found this PR #1961 which introduces the new feature.

**Comment by fthomas** [comment]
Thanks for the report, @matsluni. This is an instance of the more general problem when a project uses multiple versions of the same library which is tracked in https://github.com/scala-steward-org/scala-steward/issues/129.

**Comment by matsluni** [comment]
Thanks for the quick feedback. I will close this issue then.
