### ISSUE TITLE
sbt-github-actions: run githubWorkflowGenerate after build.sbt changes

### ISSUE THREAD

**Issue by kubukoz** [scala-steward-org/scala-steward#1984]
Follow-up to https://github.com/scala-steward-org/scala-steward/issues/1745.

Some changes in build.sbt may cause a change to the workflow files, e.g. a Scala version upgrade.

In these situations, Steward could regenerate the YAML configs as well. The exact keys that can influence that result might be hard to detect, so I guess it could run automatically on every change to `.sbt` / `.scala` build files if there's `sbt-github-actions` in the build.

**Comment by fthomas** [comment]
I like this but would restrict it to Scala updates. Nearly all Scala Steward PRs change `.sbt` or `.scala` files which means we would need to run `sbt githubWorkflowGenerate` on all updates if sbt-github-actions is used. That could slow down Scala Steward considerably because running sbt is slow.

**Comment by kubukoz** [comment]
right, if we can't reuse the previous session with a `reload` it probably doesn't make sense to run every time. 👍

**Comment by fthomas** [comment]
We do not run sbt every time a PR is created, so in most cases there is just no previous sbt session we could reuse.
