### ISSUE TITLE
A bug?

### ISSUE THREAD

**Issue by sagifogel** [scala-steward-org/scala-steward#1985]
Somehow the pull request suggests changing Scala version 2.12 to 2.13

<img width="1186" alt="Screen Shot 2021-03-01 at 21 42 11" src="https://user-images.githubusercontent.com/187556/109549751-11cae900-7ad7-11eb-8784-d78073279fb7.png">

[https://github.com/sagifogel/Proptics/pull/68](https://github.com/sagifogel/Proptics/pull/68)

Thanks.

**Comment by SethTisue** [comment]
a more general ticket in this area is https://github.com/scala-steward-org/scala-steward/issues/129

**Comment by fthomas** [comment]
Closing as duplicate of the mentioned ticket.
