### ISSUE TITLE
Could/should scala-steward scala version PRs update github actions?

### ISSUE THREAD

**Issue by nafg** [scala-steward-org/scala-steward#1996]
In particular ones generated by sbt-github-actions. It should make changes like these https://github.com/nafg/slick-additions/commit/b24524448f6e06d059d6e4724c088a40b9036d2c#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03f, otherwise the build will fail

**Comment by fthomas** [comment]
It will regenerate the workflow on the next Scala update: https://github.com/scala-steward-org/scala-steward/pull/1993

**Comment by nafg** [comment]
Amazing!

**Comment by nafg** [comment]
I guess the more you have the more you want...

What about .mergify.yml -- that has to be kept in sync with the scala
version too...

I suppose if you're updating the actions via the sbt task,I could override
the task to do it and then get it for free

**Comment by nafg** [comment]
Also the build failing is not as bad as mergify thinking it's not ready to
be merged... I could merge it manually. After all I have to mark it Ready
for Review anyway. And I can update the file after I merge it.

(Part of the issue is that since scala-steward prs are in a fork, I can't
push to the pr branch)
