### ISSUE TITLE
Feature request: run arbitrary (sbt) action after the update

### ISSUE THREAD

**Issue by vigoo** [scala-steward-org/scala-steward#1997]
I would like to run a custom sbt task after each update, before creating the update commit, that can make additional changes in the repository.

This is a very specific use case for zio-aws where scala-steward updates the full AWS SDK BOM that sometimes get new aws services included. In that case zio-aws's github actions definition must be regenerated to include the new aws libraries. I have an sbt task to do that, but it would be really nice to be able to trigger it automatically for each update.

If implemented as a general purpose extension point it would be probably useful for others too. For example it could also solve #1889

**Comment by fthomas** [comment]
We already have post update hooks (https://github.com/scala-steward-org/scala-steward/pull/1751) which can run arbitrary actions after an update. There are hooks for running [`scalafmt` and `sbt githubWorkflowGenerate`](https://github.com/scala-steward-org/scala-steward/blob/b649182c89b9955a6f12c87ca37255db268c9165/modules/core/src/main/scala/org/scalasteward/core/edit/hooks/HookExecutor.scala#L79-L109). The only thing that is missing for your feature request is that Scala Steward users can define their own hooks in their `.scala-steward.conf` files.
