### ISSUE TITLE
Sangria: update does not contain link to release

### ISSUE THREAD

**Issue by yanns** [scala-steward-org/scala-steward#2088]
Hi,

this issue is maybe a call for help, sorry for that.
I've noticed that the PR to update sangria do not contain links to release.

Ex: https://github.com/agourlay/cornichon/pull/510 does not contain a link to https://github.com/sangria-graphql/sangria/releases/tag/v2.1.3

I'm wondering if I configured something wrong here, and if the issue is coming from scala-steward.

It'd be great if someone can give me information about this.

**Comment by fthomas** [comment]
The [sangria POM](https://repo1.maven.org/maven2/org/sangria-graphql/sangria_2.13/2.1.3/sangria_2.13-2.1.3.pom) contains this URL:
```xml
<scm>
<url>https://github.com/sangria-graphql/sangria.git</url>
```
I think if it is changed to https://github.com/sangria-graphql/sangria (notice the missing `.git` at the end), Scala Steward would be able to link to the release notes.

**Comment by yanns** [comment]
Thanks @fthomas, I'll try that!
