### ISSUE TITLE
Docker image for jdk 11

### ISSUE THREAD

**Issue by froth** [scala-steward-org/scala-steward#2156]
The official scala steward docker image fails for one of my projects because part of the sbt file relies on a java11 feature. The official docker image fails to steward my project as it runs on java 8.

Would it be possible to update the image to java 11 or provide a separate Dockerfile for java 11?
I could build one myself, but I think it might be handy for other people as well.

**Comment by fthomas** [comment]
I'm fine with using Java 11 instead of 8 for the Docker image. A PR for that change would be welcome.
