### ISSUE TITLE
Git submodule deleted on dependency update

### ISSUE THREAD

**Issue by jakubjanecek** [scala-steward-org/scala-steward#2178]
We run the latest version 0.10.0 of Scala Steward internally and we noticed that during one of the dependency updates Git submodule was deleted in the PR.

![screenshot](https://user-images.githubusercontent.com/901231/125044045-df8c5200-e09b-11eb-92f9-1eb2e48a99ce.jpg)

We don't understand the change, it seems like a bug. Is there something we can configure which would prevent this or is this really a bug? I couldn't find anything related to this in configuration or other issues.

Thank you.

**Comment by fthomas** [comment]
I've no idea what could cause this. The only submodule-related code we have is https://github.com/scala-steward-org/scala-steward/blob/410dd9a6b508c329c2a3d1aa665e387c1098a2c2/modules/core/src/main/scala/org/scalasteward/core/git/FileGitAlg.scala#L88-L89
which is executed after cloning and syncing the fork if forking is enabled. My understanding is that this command is enough to bring the submodules in sync with the remote repo.
