### ISSUE TITLE
I'm taking a break

### ISSUE THREAD

**Issue by fthomas** [scala-steward-org/scala-steward#2206]
I haven't been very active in this project in recent months and only responded to smaller issues and PRs. This mode will continue until I've more time available for this project.

**Comment by exoego** [comment]
I appreciate your passion and efforts on this project 🙇  
Take a good rest !!

**Comment by fthomas** [comment]
Thank you @exoego!

**Comment by fthomas** [comment]
Btw, this issue can also be understood as a "call for maintainers".

**Comment by kubukoz** [comment]
I'm struggling real hard not to ask for promotion now :joy: currently have enough trouble with existing commitments so I can't really help this way.

Just a reminder for anyone seeing this though, I have rights to merge PRs to the https://github.com/scala-steward-org/repos/ repository so new projects can still be added/removed even without Frank's activity.

**Comment by exoego** [comment]
Though I haven't been active recently on this repo, I am interested in joining in maintainers, as a heavy Scala Steward user at work.

**Comment by exoego** [comment]
@fthomas It seems that I can not push to this repo, nor close issues/PRs.

**Comment by fthomas** [comment]
I created the @scala-steward-org/core team for the maintainers of this repo and added you to it. You should have write permissions now via this team.

**Comment by fthomas** [comment]
> do you have any advice to start to work on the repository ? Start to have a look to a PR (an easy one to start maybe)?

I'm sorry, I don't even have time for that. :-(

 
> I've decided to start by a real small one, that find useful during my research. The PR is [here](https://github.com/scala-steward-org/scala-steward/pull/2282). :)

Thanks you!

**Comment by fthomas** [comment]
> I haven't been very active in this project in recent months and only responded to smaller issues and PRs.

I'm going to close this issue and declare this state the new normal for me now. :-)
