### ISSUE TITLE
Throws if both groupIdBefore and artifactIdBefore is missing

### ISSUE THREAD

**Issue by exoego** [scala-steward-org/scala-steward#2238]
https://github.com/scala-steward-org/scala-steward/pull/2237#discussion_r711900481

**Comment by fthomas** [comment]
Note that `groupIdBefore` can be missing if `artifactIdBefore` is set. At least one of these two must be set.

**Comment by fthomas** [comment]
We could also change the fields and/or types of `ArtifactChange` https://github.com/scala-steward-org/scala-steward/blob/812a0b3b544383074a9ace1b6fd13deb2402d610/modules/core/src/main/scala/org/scalasteward/core/update/ArtifactMigrations.scala#L104-L110 such that it is impossible to construct an incomplete instance.
