### ISSUE TITLE
Support `replace:` Scalafix rules?

### ISSUE THREAD

**Issue by fthomas** [scala-steward-org/scala-steward#2327]
TIL that Scalafix can rename symbols via a simple command, for example this renames `Nel` to `Nelly` in this code base:
```
sbt:scala-steward> core/scalafix replace:org.scalasteward.core.util.Nel/org.scalasteward.core.util.Nelly
```
It might be useful to support such ad hoc rules for updates that only require some simple renamings. The [fs2 3.0.6 to 3.1.0 update](https://github.com/scala-steward-org/scala-steward/pull/2192) comes to mind here where `utf8Decode` needed to be renamed to `utf8.decode`. If such simple replacements can be accomplished via the `replace:` command, we should support that.

**Comment by fthomas** [comment]
Wow, this command
```
sbt:scala-steward> core/scalafix replace:fs2.text.utf8.decode/fs2.text.utf8DecodeFoo
```
produced the following diff:
```diff
diff --git a/modules/core/src/main/scala/org/scalasteward/core/io/process.scala b/modules/core/src/main/sc
ala/org/scalasteward/core/io/process.scala
index 5228d32d..8acf1706 100644
--- a/modules/core/src/main/scala/org/scalasteward/core/io/process.scala
+++ b/modules/core/src/main/scala/org/scalasteward/core/io/process.scala
@@ -87,7 +87,7 @@ object process {
   private def readInputStream[F[_]](is: InputStream)(implicit F: Sync[F]): Stream[F, String] =
     fs2.io
       .readInputStream(F.pure(is), chunkSize = 4096)
-      .through(fs2.text.utf8.decode)
+      .through(_root_.fs2.text.utf8DecodeFoo)
       .through(fs2.text.lines)
 
   private def makeMessage(prefix: String, output: List[String]): String =
diff --git a/modules/core/src/main/scala/org/scalasteward/core/util/HttpJsonClient.scala b/modules/core/src/main/scala/org/scalasteward/core/util/HttpJsonClient.scala
index 7794d681..e7947347 100644
--- a/modules/core/src/main/scala/org/scalasteward/core/util/HttpJsonClient.scala
+++ b/modules/core/src/main/scala/org/scalasteward/core/util/HttpJsonClient.scala
@@ -108,7 +108,7 @@ final class HttpJsonClient[F[_]](implicit
       method: Method,
       response: Response[F]
   ): F[Throwable] = {
-    val body = response.body.through(fs2.text.utf8.decode).compile.string
+    val body = response.body.through(_root_.fs2.text.utf8DecodeFoo).compile.string
     body.map(UnexpectedResponse(uri, method, response.headers, response.status, _))
   }
 }
```
Notice that `utf8DecodeFoo` does not exist for the renaming to succeed so it is suitable as migration in Scala Steward.

**Comment by fthomas** [comment]
LOL, this already works without any modifications to Scala Steward. This migration added to [`scalafix-migrations.conf`](https://github.com/scala-steward-org/scala-steward/blob/8e4970db22ed448af068371a1e7cac4f1ea594b8/modules/core/src/main/resources/scalafix-migrations.conf)
```
  {
    groupId: "co.fs2",
    artifactIds: ["fs2-.*"],
    newVersion: "3.1.0",
    rewriteRules: ["replace:fs2.text.utf8Decode/fs2.text.utf8.decode"]
  },
```
produced the PR https://github.com/scala-steward-org/test-repo-2/pull/65 which replaced `utf8Decode` with `utf8.decode`.

**Comment by olafurpg** [comment]
FWIW the `replace:` rule doesn't take into account inheritance so you need to repeat the renames for all concrete and abstract signatures of a method

**Comment by fthomas** [comment]
That is good to know, thanks @olafurpg. Is there documentation about `replace:` that I could link to in our own [docs](https://github.com/scala-steward-org/scala-steward/blob/master/docs/scalafix-migrations.md)? I could imagine that more people would add migrations as above to Scala Steward if they are that easy to write. :-)

Btw, I learned about `replace:` via your comment in https://github.com/scalacenter/advisoryboard/pull/79#discussion_r740926664. :smiley_cat:

**Comment by olafurpg** [comment]
The `replace:` feature isn't documented publicly because it produces broken code in some cases https://github.com/scalacenter/scalafix/blob/b3ed5279c372b00538f062634b290d7b58056161/scalafix-core/src/main/scala/scalafix/patch/Patch.scala#L147-L150

**Comment by fthomas** [comment]
Hmm, too bad. Would you (or the other Scalafix maintainers) mind if it would be more publicized by using it in Scala Steward? This looks too good not to use it.

/cc @mlachkar @bjaglin

**Comment by bjaglin** [comment]
For the record, I filed https://github.com/scalacenter/scalafix/issues/1168 to centralize the discussion about this. I haven't looked into the current limitations so it's hard for me to assess the bad publicity broken code could bring to Scalafix/Steward, but I guess advertising it in Steward would drive interest in / focus on improving the current behavior (for myself or for other contributors). I believe we should add a comment referencing the open ticket whenever we use it in `scalafix-migrations.conf` examples or central configuration.

**Comment by fthomas** [comment]
> I believe we should add a comment referencing the open ticket whenever we use it in `scalafix-migrations.conf` examples or central configuration.

Sounds good to me. I added the following comment to the migration added in #2328:
```
  {
    groupId: "co.fs2",
    artifactIds: ["fs2-.*"],
    newVersion: "3.0.7",
    // Note that the replace rule can generate broken code in some cases.
    // See https://github.com/scalacenter/scalafix/issues/1168 for details.
    rewriteRules: [
      "replace:fs2.text.utf8Decode/fs2.text.utf8.decode",
      "replace:fs2.text.utf8DecodeC/fs2.text.utf8.decodeC",
      "replace:fs2.text.utf8Encode/fs2.text.utf8.encode",
      "replace:fs2.text.utf8EncodeC/fs2.text.utf8.encodeC"
    ],
    executionOrder: "post-update"
  },
```
