### ISSUE TITLE
Unrecognized argument: --default-repo-conf

### ISSUE THREAD

**Issue by ant8e** [scala-steward-org/scala-steward#2344]
I noticed recently that my own gitlab CI based run of scala-steward started to fail. 
It seems that the command line option `--default-repo-conf` has been removed recently (but still mentionned [here](https://github.com/scala-steward-org/scala-steward/blob/master/docs/running.md)  )

At the same time, a new `--repo-config` argument has been introduced, as well as a `--disable-default-repo-config ` boolean argument. 

Could you please clarify how is it supposed to work and how to point scala-steward to a default configuration.

**Comment by fthomas** [comment]
This has been changed in https://github.com/scala-steward-org/scala-steward/pull/2337. Just replace `--default-repo-conf` with `--repo-config` and everything should work as before.
