### ISSUE TITLE
Do not hardcode sbt-scalafix version

### ISSUE THREAD

**Issue by fthomas** [scala-steward-org/scala-steward#2357]
We currently hardcode the version of sbt-scalafix that we add to the global sbt plugins temporarily while applying Scalafix migrations: 
https://github.com/scala-steward-org/scala-steward/blob/cc04fcf0e92a469b600d647631d1a417b1bf035d/modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/package.scala#L41

This is not ideal for Scala Steward instances that do not track the latest changes from this repository. If a new sbt-scalafix version is released that supports newer Scala versions, Scala Steward instances that not yet include that latest sbt-scalafix version might not successfully apply Scalafix migrations in projects that are already on the new Scala version. I think it would be better to use the latest sbt-scalafix version from the `VersionsCache`.

**Comment by bjaglin** [comment]
With the upcoming https://github.com/scalacenter/sbt-scalafix/pull/292, `scalafixEnable` will be able to work with future Scala versions (i.e. published after the release of the `sbt-scalafix` running). I am wondering if it's not better to revert this change for the sake of a more deterministic behavior?
