### ISSUE TITLE
Scala Steward generating invalid release links

### ISSUE THREAD

**Issue by daddykotex** [scala-steward-org/scala-steward#2363]
Hi, thanks again for Scala Steward.

I've hit a new bug with our installation/operating of Scala Steward. 

**Information**

- Version: Scala Steward v0.12.0
- VCS: private GitLab instance

**The problem**

My understanding is that when you configure `homepage` in your sbt build, it ends up in the pom. And when Scala Steward reads that pom it grabs the URL to generate the `ReleaseRelatedUrl`. When using a private GitLab instance, or atleast in the way it's configured for us, trying to do a `HEAD` to a file (eg: "https://internal.gitlab.company.com/tools/scala/some-project/blob/master/ReleaseNotes.md") will give you a 302 with a `Location: https://internal.gitlab.company.com/users/sign_in`.

Because the `OkHttpClient` in use by the `UrlChecker` follows redirect, this ends up with a `200 OK` and thus the file url is considered valid when, in reality, it most likely is not.

eg:

![Screen Shot 2021-11-17 at 12 12 17](https://user-images.githubusercontent.com/5230460/142248733-32c7973e-6901-4238-9ec5-070c4668f8a7.png)

**The possible solutions:**

1. disable redirect for the http client (I don't know if that's possible, especially when you consider the behaviour of GitHub when renaming a repo (redirects to the new one, eg: `fthomas/scala-steward` now points to this repository.))
2. have an alternative client with redirect disabled only for url checking
3. use the gitlab api (authenticated) to check for files existence (https://docs.gitlab.com/ee/api/repository_files.html)

Personally, I would consider the second, and if that does not work the third one.

What do you think?

Thanks

**Comment by fthomas** [comment]
> Because the `OkHttpClient` in use by the `UrlChecker` follows redirect, this ends up with a `200 OK` and thus the file url is considered valid when, in reality, it most likely is not.

With #916 we considered redirects as non-existent but we did not use `OkHttpClient` back then. It is unfortunate that this behaviour depends on the underlying client implementation. I would prefer a solution where the `UrlChecker` does not follow redirects.

**Comment by daddykotex** [comment]
See the ugly hack MR that I've created, I did not add tests, I'm hoping you tell me it's ok or not before I proceed.
