### ISSUE TITLE
Feature request: Sign-off the Git commit

### ISSUE THREAD

**Issue by hrj** [scala-steward-org/scala-steward#2408]
[Background](https://stackoverflow.com/questions/1962094/what-is-the-sign-off-feature-in-git-for)

This will help repositories which have a DCO check, for example in [this repo](https://github.com/librecaptcha/lc-core/pull/106)

Of course, Scala Steward isn't a legal entity and the commits are very small anyway, so it doesn't really matter from a legal POV. The sign-off will only make the process of merging the PR smoother.

**Comment by fthomas** [comment]
I don't mind if Scala Steward does this. Dependabot [does it too](https://github.com/scala-steward-org/scala-steward-action/commit/9b827e22a3bb91439e9277f498e4df237306644b).

It is as easy as adding `--signoff` to [this line](https://github.com/scala-steward-org/scala-steward/blob/v0.24.0/modules/core/src/main/scala/org/scalasteward/core/git/FileGitAlg.scala#L69).

**Comment by michaelmior** [comment]
Just wanted to ping this again. I use the [DCO](https://github.com/apps/dco) to check that PRs have been signed off. Because scala-steward doesn't currently do this, all the PRs show up as failing. It's not a big deal to work around, but it would be a nice usability improvement.
