### ISSUE TITLE
Question - dependencies only in private repositories

### ISSUE THREAD

**Issue by nicwaters456** [scala-steward-org/scala-steward#2410]
I am running Scala Steward with Docker, for private repositories - all working nicely for external dependencies.

There's just one thing I'm not clear on - should Steward be able to create PRs for private dependencies that a repository uses? i.e. dependencies only present in our private artifact repository?

I've run Steward in trace mode and it seems to have no problem connecting to our private artifact repository; and the logs show that it is registering that a private dependency is in use by a given build, for e.g.

`[TRACE { "groupId": "private-group", "artifactId": { "name": "private-group-artifact", "maybeCrossName": "private-group-artifact_2.13" }, "version": "0.0.xxxx", "sbtVersion": null, "scalaVersion": null, "configurations": null }`

But it doesn't create a PR and nor does it log, for example:

`INFO  Ignore xxx.yyy:(AAA BBB_2.13) : 0.a.b -> 0.e.d ​(reason: no suitable next version)`

It just seems to ignore them entirely. Is there something I need to configure, or should it be ignoring private dependencies?

(apologies if this is a question covered somewhere in a doc, I've had a look around and couldn't find anything, but perhaps I am missing something obvious)

**Comment by exoego** [comment]
Maybe this if your private dependencies are published on Sonatype Nexus 3 https://github.com/scala-steward-org/scala-steward/issues/1628

**Comment by nicwaters456** [comment]
Interestingly in trace mode Steward does produce logs like this:

` DEBUG not found: https://internal.repo.path/maven/maven/etc/etc-etc-2.13/maven-metadata.xml`

and I wondered if related - but I saw it producing the same type of log for external libraries and thought perhaps not.

(we are using AWS CodeArtifact)

**Comment by exoego** [comment]
Are credentials for CodeArifact setup in sbt and available for Steward?

**Comment by nicwaters456** [comment]
> Are credentials for CodeArifact setup in sbt and available for Steward?

yes - and Steward seems to have no errors reaching CodeArtifact. The only log of interest that I could see was the 'not found' (pasted above) when it tries to get the Maven Metadata file.

**Comment by er1c** [comment]
I have a similar issue with a custom maven resolver https://github.com/EVENFinancial/fm-sbt-s3-resolver/blob/master/src/sbt-test/fm-sbt-s3-resolver/scala-steward/src/test/scala/ScalaStewardTest.scala#L25
