### ISSUE TITLE
How to ask scala-steward to sign CLA?

### ISSUE THREAD

**Issue by catap** [scala-steward-org/scala-steward#2428]
Good day!

Is it possible to ask someone to sign CLA on behalf of scala-steward?

If yes, maybe it is good idea to document such steps somewhere?

**Comment by catap** [comment]
Relevant topic: https://github.com/scala-steward-org/scala-steward/issues/2408

**Comment by fthomas** [comment]
I'm the only one who has access to the @scala-steward GitHub user and I don't sign CLAs on behalf of it (anymore). I recommend to configure the CLA checker such that it ignores PRs by @scala-steward. (For example, [here are instructions how to do this with cla-assistant](https://github.com/cla-assistant/cla-assistant#can-i-allow-bot-user-contributions).)

**Comment by catap** [comment]
@fthomas thanks, that's clear.
