### ISSUE TITLE
unexpected value when using `--do-not-fork=true`

### ISSUE THREAD

**Issue by yanns** [scala-steward-org/scala-steward#2437]
We are running scala steward once per week on private repositories, with the argument `--do-not-fork=true`.
This is running very well since months.

Since last Sunday, the job is failing with the following error:
```
Got unexpected value for flag: --do-not-fork
```

Was there any change here?

**Comment by mzuehlke** [comment]
The CLI parameter `--do-not-fork` is just a flag and does not expect an argument.

In #2414 [case-app](https://github.com/alexarchambault/case-app) got replaced with [decline](https://ben.kirw.in/decline/) for command-line arguments parsing. Probably case-app was less strict with the parsing.

**Comment by yanns** [comment]
Using only `--do-not-fork` works. Thanks for the quick feedback.
