### ISSUE TITLE
Prevent updates from "normal" versions to hashes

### ISSUE THREAD

**Issue by fthomas** [scala-steward-org/scala-steward#2483]
See #2359 and https://github.com/scalameta/metals-gitpod-sample/pull/85 for example.

bloop-config and sbt-bloop are example artifacts that have a few hash versions:
* https://repo1.maven.org/maven2/ch/epfl/scala/bloop-config_2.12/
* https://repo1.maven.org/maven2/ch/epfl/scala/sbt-bloop_2.12_1.0/

**Comment by kittsville** [comment]
I've recently encountered an incorrect upgrade from `1.4.12` to another old artefact: [`1032048a`](https://mvnrepository.com/artifact/ch.epfl.scala/bloop-backend_2.12/1032048a). This has affected some open source repos such as [zio-redis](https://github.com/zio/zio-redis/actions/runs/1742302278).

I'm not aware of Scala Steward's internals, but could the artefact's published date be used to sense check these upgrades? Bloop `1.4.12` was published Jan 2022, while `1032048a` was published Jan 2018.

**Comment by fthomas** [comment]
> I'm not aware of Scala Steward's internals, but could the artefact's published date be used to sense check these upgrades?

That could help but unfortunately we do not have them and don't get them when we query the versions from Coursier.
