### ISSUE TITLE
No updates to github.com/nafg/scala-phonenumber

### ISSUE THREAD

**Issue by nafg** [scala-steward-org/scala-steward#2510]
For a while the build was broken but I fixed it. Did it flag it or something, or am I missing something?

**Comment by fthomas** [comment]
@scala-steward ignores broken projects for 7 days, see https://github.com/scala-steward-org/scala-steward/pull/997.

**Comment by nafg** [comment]
Ok that's fine, thanks for the info.

If you implement https://github.com/scala-steward-org/scala-steward/issues/2030 it could mention that in the comment
