### ISSUE TITLE
Support for setting required number of reviewers on GitLab merge requests

### ISSUE THREAD

**Issue by dkichler** [scala-steward-org/scala-steward#2519]
This feature would be useful for helping automate merging ScalaSteward MRs in the context where most other MRs are subject to minimum reviewer rules.  

This would be mostly to support running ScalaSteward over private repositories where credentials provided through runtime parameters would require the sufficient privileges for this operation through the GitLab API.

**Comment by dkichler** [comment]
A bit more rationale for this feature request:
- Ideally this would be achievable through more dynamic MR approval rules in GitLab.  This is on their roadmap, but until then this feature would greatly help automate our ScalaSteward process.
- Trying to keep our solution open source and the free tier of Mergify does not support the features we would need to replicate this solution.

**Comment by exoego** [comment]
> This is on their roadmap, but until then this feature would greatly help automate our ScalaSteward process.

Could you share the link to the roadmap?
After GitLab released it, we may remove this feature.

**Comment by dkichler** [comment]
> Could you share the link to the roadmap?
After GitLab released it, we may remove this feature.

The feature request I was watching is this one:   https://gitlab.com/gitlab-org/gitlab/-/issues/282495

It looks like they've already backed away from it (not uncommon)
