### ISSUE TITLE
Scala steward seems to sleep on my repository

### ISSUE THREAD

**Issue by dylandoamaral** [scala-steward-org/scala-steward#2574]
Hello guys,

first of all, thank you for your amazing little cat robot, it is trully helpful !

Sadly since almost two months, the little kitty seems to sleep for no reason (the repo is https://github.com/univalence/zio-spark) . 

As an example, I saw scala steward update scalafmt to 3.5.1 in other repositories, mine is 3.3.1 and nothing is happening.

I tried to find where I can check the scala steward logs but I found nothing.

**Comment by fthomas** [comment]
The public Scala Steward has been shut down (https://twitter.com/fst9000/status/1532088018084978689) but may be [turned on again in the future](https://contributors.scala-lang.org/t/can-scala-maintain-a-public-scala-steward-instance/5754). Anyway, this repo is about the development of the Scala Steward software. Inquiries about specific instances and their logs should be raised in the repo where you added your repository to that instance's repos list.
