### ISSUE TITLE
Use coursier repo specific authentication settings

### ISSUE THREAD

**Issue by 987Nabil** [scala-steward-org/scala-steward#2575]
Via the sbt the setting `csrConfiguration` it is possible to add not only repo specific basic auth, but also add headers to authenticate via OAuth2 for example. This is (as far as I am aware of) the only way to set headers without using a custom URL resolver.

Scala Steward should also be able to read this setting.

Related
https://github.com/sbt/sbt/issues/4382

**Comment by 987Nabil** [comment]
Actually #2533 should solve this.

**Comment by fthomas** [comment]
Closing since #2533 has been merged.
