### ISSUE TITLE
Also update scripts that download scalafmt

### ISSUE THREAD

**Issue by ekrich** [scala-steward-org/scala-steward#2586]
Scala Native was an early adopter of `scalafmt` and uses a script to download the correct version. The script is used locally at the command line and also during CI to check the format. I have copied this approach in `sconfig` so it would be great to have the script updated as part of the PR.

Recently I got this PR - https://github.com/ekrich/sconfig/commit/c2c89a2bbf2c6d4392040bc67720899a0abcf3b5

It would be great if this line could also be updated. https://github.com/ekrich/sconfig/blob/main/scripts/scalafmt#L7

The work around could be to use `sbt-scalafmt` but we are hoping to get a Scala Native version of `scalafmt` eventually and this would somewhat break the idea of a fast starting version. `scala-cli` may also be a future download option rather than Coursier.

**Comment by mzuehlke** [comment]
You could try to make the `.scalafmt.conf` the source of truth:
``` 
VERSION=$(sed -nre "s#\s*version[^0-9]+([0-9.]+)#\1#p" $HERE/.scalafmt.conf)
```

**Comment by ekrich** [comment]
That is a very good idea although that `sed` is pretty scary.

**Comment by ekrich** [comment]
I put it in here but we also use this script in Scala Native too - hope co-author is ok.
https://github.com/ekrich/sconfig/pull/277/commits/153ef9105d526644fd59c74318e1af1ded4eb1b0

**Comment by mzuehlke** [comment]
Yes, `sed` can be scary 😉 . I'm happy, if it helps you.
Co-author is more than ok.

**Comment by ekrich** [comment]
I guess people could also have `version = "3.5.9"`. Not sure if that is correct or not but.

**Comment by fthomas** [comment]
@ekrich can we close this issue?

**Comment by ekrich** [comment]
Workaround above is a good solution for scripts that call `scalafmt`. Thanks!
