### ISSUE TITLE
suggestion - setting "latest" Docker tag for stable releases only

### ISSUE THREAD

**Issue by bcarter97** [scala-steward-org/scala-steward#2613]
I've noticed that every time a `-SNAPSHOT` gets pushed to DockerHub, it is tagged as the latest version. I wonder if it would make more sense to only set the `latest` tag when it is a stable release and not a snapshot.

**Comment by arixmkii** [comment]
In case if this implemented it would be nice to have `fthomas/scala-steward-snapshot:latest` published for every snapshot going on. As there are active users of the current behavior and they deserve to keep this alternative.

**Comment by fthomas** [comment]
Is it possible to tweak the build so that stable releases are tagged with a new `latest-release` tag? We would then have tags for releases and snapshots and wouldn't change the meaning of the `latest` tag.

**Comment by fthomas** [comment]
> I can raise a pr for this if you like.

That would be appreciated.
