### ISSUE TITLE
Ensure that all maintainers can publish new Scala Steward versions

### ISSUE THREAD

**Issue by fthomas** [scala-steward-org/scala-steward#2620]
In the past I was the only one publishing Scala Steward versions (via [scripts/release.sh](https://github.com/scala-steward-org/scala-steward/blob/c99d9d2c8ffe6261fad7378fdee7eb1a274cd732/scripts/release.sh)). I would like to enable all members of @scala-steward-org/core (:wave:  @exoego @mzuehlke) to publish new versions if you want to. Is there anything I need to do so that you can publish new versions? Maybe someone just needs to try it and see what fails.

**Comment by exoego** [comment]
Hi, Thomas.
First of all, many thanks for your long contributions to Scala ecosystems with Scala Steward.

I suggest to setup https://github.com/sbt/sbt-ci-release so any maintainers can publish new versions without keeping secrets like the Sonatype token or password.

**Comment by fthomas** [comment]
We're already using sbt-ci-release. Maybe should just try running the `scripts/release.sh` and see if everything works. :-)

**Comment by exoego** [comment]
Oh, I was not aware of that 😅 
I will review the existing PRs and try running `scripts/release.sh` in a few days.

**Comment by henricook** [comment]
That'd be great @exoego - i'm very much looking forward to using `dependencyOverrides` when the next release is tagged

**Comment by exoego** [comment]
Sorry for long delay.

I tried `scripts/releas.sh` and encountered:
```
$ ./scripts/release.sh 0.15.0
error: gpg failed to sign the data
error: unable to sign the tag
Enumerating objects: 14, done.
Counting objects: 100% (14/14), done.
Delta compression using up to 10 threads
Compressing objects: 100% (14/14), done.
Writing objects: 100% (14/14), 10.58 KiB | 174.00 KiB/s, done.
Total 14 (delta 0), reused 14 (delta 0), pack-reused 0
To https://github.com/exoego/scala-steward.git
 * [new tag]           v0.10.0 -> v0.10.0
 * [new tag]           v0.11.0 -> v0.11.0
 * [new tag]           v0.12.0 -> v0.12.0
 * [new tag]           v0.13.0 -> v0.13.0
 * [new tag]           v0.14.0 -> v0.14.0
 * [new tag]           v0.3.0 -> v0.3.0
 * [new tag]           v0.4.0 -> v0.4.0
 * [new tag]           v0.5.0 -> v0.5.0
 * [new tag]           v0.6.0 -> v0.6.0
 * [new tag]           v0.7.0 -> v0.7.0
 * [new tag]           v0.8.0 -> v0.8.0
 * [new tag]           v0.8.1 -> v0.8.1
 * [new tag]           v0.9.0 -> v0.9.0
 * [new tag]           v0.9.1 -> v0.9.1
```

**Comment by fthomas** [comment]
> error: gpg failed to sign the data
error: unable to sign the tag

Looks like signing the tag didn't work.

**Comment by exoego** [comment]
Is it OK to cut a new release (tag) from GitHub UI https://github.com/scala-steward-org/scala-steward/releases/new ?

**Comment by fthomas** [comment]
0.16.0 was released yesterday and it wasn't me. :-) So I guess someone from @scala-steward-org/core created a new tag via GitHub's web interface. Unfortunately the tag is signed with a key owned by GitHub, so I don't know who created that tag, but it demonstrates that any maintainer can publish new releases and this ticket can be closed.

**Comment by armanbilge** [comment]
> Unfortunately the tag is signed with a key owned by GitHub, so I don't know who created that tag

Based on the CI job I'm guessing @alejandrohdezma? :)
https://github.com/scala-steward-org/scala-steward/actions/runs/3511909519

**Comment by exoego** [comment]
I do not. Probably alenajdro.

**Comment by alejandrohdezma** [comment]
Yeah, it was me. BTW I'm working on a new proposal for the CI to have semi-automated releases, so that the features do not accumulate for months on end. Something similar to what we have for the https://github.com/scala-steward-org/scala-steward-action. WDYT?

**Comment by fthomas** [comment]
Sounds good to me!

I'm closing this since we now have proof that I'm not the only one who can publish new versions.
