### ISSUE TITLE
Add reformatting commits to `.git-blame-ignore-revs`

### ISSUE THREAD

**Issue by armanbilge** [scala-steward-org/scala-steward#2644]
See:
- https://github.com/scalameta/metals/pull/4050#issuecomment-1162053591
- https://github.com/http4s/http4s/issues/6483

Git and GitHub support automatically omitting commits from `git blame` via a `.git-blame-ignore-revs`. Common candidates are reformatting commits, for which Steward is often responsible when updating Scalafmt. It would be super-duper cool if it could execute a post-post-commit-hook that adds the formatting commit to `.git-blame-ignore-revs`.

**Comment by fthomas** [comment]
Duplicate of #2567.

**Comment by armanbilge** [comment]
Woops, sorry! Convinced I had an original thought here 😉
