### ISSUE TITLE
Support for Azure Repos

### ISSUE THREAD

**Issue by vidalgp** [scala-steward-org/scala-steward#2659]
Helloo,
I was wondering if there is any intention to support azure in the future (particularly azure DevOps git repos).
I tried [Renovate](https://docs.renovatebot.com/setup-azure-devops/), but it's nothing compared to what scala-steward accomplishes in a Scala project.

Cheers

**Comment by exoego** [comment]
PR welcome

**Comment by robinraju** [comment]
@exoego @vidalgp I created a PR to add support for Azure repos over the weekend. I tested it on my personal account, and it works as expected.

**Comment by fthomas** [comment]
Fixed by #2837.
