### ISSUE TITLE
dependencyOverrides having no effect (or I'm using it wrong) in 0.15.0

### ISSUE THREAD

**Issue by henricook** [scala-steward-org/scala-steward#2674]
Hi all,

I run scala steward daily, against a repo in my self hosted Gitlab. Since the 0.15.0 release I've been trying to limit how often PRs get raised for S3 and AWS library updates.

I'm using this config:

```
dependencyOverrides = [
  {
    dependency = { groupId = "com.amazonaws" },
    pullRequests = { frequency = "14 day" },
  },
  {
    dependency = { groupId = "software.amazon.awssdk" },
    pullRequests = { frequency = "14 day" },
  },
]
```

This is output by steward when running in the 'Parsed Repo Config' log entry, which implies to me that it's valid config:

![image](https://user-images.githubusercontent.com/82004/180161220-f9750df8-7689-4af6-a48d-d62c465fdc66.png)

Unfortunately over the last three days I've had MRs from both of these groupIds, a couple of screenshots below. Am I doing something wrong? Is my group id incorrect? Or could the feature be faulty?

I don't see any errors around the point where Steward raises these MRs/finds these dependencies awaiting update.

![image](https://user-images.githubusercontent.com/82004/180161432-13fb9911-2775-4871-af9e-59e5234cb296.png)

**Comment by exoego** [comment]
The feature uses the previous pull requests to calculate how many days passed.
If your Scala Steward instance had  not created any PRs to the dependency, PR will be created regardless of configuration.

**Comment by henricook** [comment]
Hi @exoego - thanks for your answer.

I've been merging the ones that have been created over the last few days, so there's history that I guess it should be able to see

**Comment by exoego** [comment]
Is the workspace persisted for your Scala Steward instance?
Ref. https://github.com/scala-steward-org/scala-steward/blob/main/docs/running.md

**Comment by henricook** [comment]
It is not, that'll be it. Thanks - i'll look into it!
