### ISSUE TITLE
How to ignore PR state while updating a dependency

### ISSUE THREAD

**Issue by fredshonorio** [scala-steward-org/scala-steward#2687]
In the PRs created by scala-steward the following message appears:
> If you'd like to skip this version, you can just close this PR. 

For the purposes of organization I want to close PRs freely, without accidentally ignoring that dependency from that point forward (which, by my quick reading of the code in `NurtureAlg.processUpdate` is what happens). I'd like to declare that configuration (pin, ignore, etc) only in the config file.

Is there a way to achieve do this now? If not I could attempt a PR, is it a useful feature?

**Comment by exoego** [comment]
Sorry, I do not get the title and description.
It would be helpful if you rephrase or add more details.

If you are searching how to ignore, or slowdown future updates, please refer https://github.com/scala-steward-org/scala-steward/blob/main/docs/repo-specific-configuration.md

**Comment by fredshonorio** [comment]
@exoego I've added more detail

**Comment by fredshonorio** [comment]
Ok I realize (thanks Arman) that closing the scala-steward PR only ignores the specific version, so it does not ignore every subsequent update like I feared. I'll close the issue now.
