### ISSUE TITLE
[feature request] Support for Mill plugins

### ISSUE THREAD

**Issue by ckipp01** [scala-steward-org/scala-steward#2694]
From looking at the code here:

https://github.com/scala-steward-org/scala-steward/blob/a2954c3d09f9ed01aaed377a0674aba5a60f90e5/modules/mill-plugin/src/main/scala/org/scalasteward/mill/plugin/StewardPlugin.scala#L44-L45

I see that Steward only considers dependencies in modules, and also the Mill version itself from [here](https://github.com/scala-steward-org/scala-steward/blob/a2954c3d09f9ed01aaed377a0674aba5a60f90e5/modules/core/src/main/scala/org/scalasteward/core/buildtool/mill/MillAlg.scala#L87-L88). However, this misses out on the Mill plugins that are included in the actual build itself like this:

```
import $ivy.`com.goyeau::mill-scalafix::0.2.10`
import $ivy.`de.tototec::de.tobiasroeser.mill.integrationtest::0.6.1`
import $ivy.`de.tototec::de.tobiasroeser.mill.vcs.version::0.2.0`
...
```

There really isn't a way to pull this information from Mill as far as I'm aware, so it'd need to manually be put together. It'd also have to consider the Mill version because take `com.goyeau::mill-scalafix::0.2.10` for example. The artifact is actually `mill-scalafix_mill0.10_2.13` to support the current `0.10.x` series of Mill.

One potential way to grab these would be to just regex them since they're almost always in this format at the to of the file. You could do this after grabbing the Mill version, and then put the artifact name together. This would then allow for PRs to also be sent in for these, which are currently missed.

**Comment by lefou** [comment]
* See also #1504
