### ISSUE TITLE
Fallback to `.github/.scala-steward.conf` if config not found in root

### ISSUE THREAD

**Issue by mkurz** [scala-steward-org/scala-steward#2735]
I think it's a good idea to fall back to the `.github` directory when loading the config.
It's getting more and more a convention to put things GitHub related in that folder. E.g. see our repo: https://github.com/playframework/playframework/tree/main/.github
~We will also move the `.mergify.yml` from the root to `.github` soon, so `.scala-steward.conf` is the last one missing.~ Done!

The change needs to be done in
* https://github.com/scala-steward-org/scala-steward/blob/main/modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfigAlg.scala
* maybe here too (?): https://github.com/scala-steward-org/scala-steward/blob/main/modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfigLoader.scala
* Update docs: https://github.com/scala-steward-org/scala-steward/blob/main/docs/repo-specific-configuration.md (maybe there is more, not sure)

**Comment by fthomas** [comment]
> I think it's a good idea to fall back to the `.github` directory when loading the config.

Sounds good to me. For people that use Scala Steward with Bitbucket or GitLab it would also be nice to be able to unclutter their root directories without using a `.github` directory. Maybe falling back to a generic `.config` directory would also be a good idea. See also https://github.com/dot-config/dot-config.github.io


> * maybe here too (?): https://github.com/scala-steward-org/scala-steward/blob/main/modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfigLoader.scala

This does not need to be changed.
