### ISSUE TITLE
Run `scala-collection-compat` on update to Scala 2.13

### ISSUE THREAD

**Issue by EwoutH** [scala-steward-org/scala-steward#2770]
When the Scala is bumped to 2.13, it would be great if the [scala-collection-compat](https://github.com/scala/scala-collection-compat) migration rules could be ran.

```scala
dependency:Collection213Upgrade@org.scala-lang.modules:scala-collection-migrations:2.8.1
```

**Comment by exoego** [comment]
For volunteer, https://github.com/scala-steward-org/scala-steward/blob/main/modules/core/src/main/resources/scalafix-migrations.conf should be updated

**Comment by alifirat** [comment]
Hey @EwoutH
The migration rule should be apply when the scala version is bumped from "2.12.X" to "2.13.X" right?

**Comment by EwoutH** [comment]
Hi @alifirat! Yes, that should be the case.

**Comment by fthomas** [comment]
@EwoutH, can this be closed?

**Comment by EwoutH** [comment]
Thanks for this effort. I correctly attempted the run when updating to Scala 2.13, but in our setup it unfortunately failed. But that could also be due to the rule itself. See the [log here](https://github.com/EwoutH/NetLogo/actions/runs/3752758458/jobs/6375284107#step:6:213).

(CC @SethTisue)

**Comment by fthomas** [comment]
The errors in the logs are:
```
2022-12-21 21:01:39,318 INFO  Running migration ScalafixMigration(org.scala-lang,NonEmptyList(scala-library, scala-compiler, scala-reflect, scalap),2.13.0,NonEmptyList(dependency:Collection213Upgrade@org.scala-lang.modules:scala-collection-migrations:2.8.1),Some(https://github.com/scala/scala-collection-compat#collection213upgrade),Some(NonEmptyList(-P:semanticdb:synthetics:on)),None,None,None)
2022-12-21 21:02:12,628 WARN  Scalafix migration failed
java.io.IOException: '"SBT_OPTS=-Xmx2048m -Xss8m -XX:MaxMetaspaceSize=512m" sbt -Dsbt.color=false -Dsbt.log.noformat=true -Dsbt.supershell=false ;scalafixEnable;scalafixAll dependency:Collection213Upgrade@org.scala-lang.modules:scala-collection-migrations:2.8.1' exited with code 1
...
Error:  scalafix.interfaces.ScalafixException: Failed to fetch [Dependency(Module(ch.epfl.scala, scalafix-cli_2.12.17), 0.10.4, configuration=runtime)]from [ApiRepo(IvyRepository(Pattern(List(Const(file:/home/runner/.ivy2/local/), Var(organisation), Const(/), Var(module), Const(/), Opt(List(Const(scala_), Var(scalaVersion), Const(/))), Opt(List(Const(sbt_), Var(sbtVersion), Const(/))), Var(revision), Const(/), Var(type), Const(s/), Var(artifact), Opt(List(Const(-), Var(classifier))), Const(.), Var(ext))), None, None, true, true, true, true, None, true)), ApiRepo(MavenRepository(https://repo1.maven.org/maven2, None, None, true, true)), MavenRepository(https://oss.sonatype.org/content/repositories/public)]
Error:  	at scalafix.internal.interfaces.ScalafixCoursier.fetch(ScalafixCoursier.java:30)
...
Error:  Caused by: coursierapi.error.DownloadingArtifactsError: https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.12.17/scala-compiler-2.12.17.jar: download error: Caught java.nio.file.NoSuchFileException (/home/runner/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.12.17/.scala-compiler-2.12.17.jar.part -> /home/runner/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.12.17/scala-compiler-2.12.17.jar) while downloading https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.12.17/scala-compiler-2.12.17.jar
```

I don't know why this failed. [ch.epfl.scala:scalafix-cli_2.12.17:0.10.4](https://search.maven.org/artifact/ch.epfl.scala/scalafix-cli_2.12.17/0.10.4/jar) and https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.12.17/scala-compiler-2.12.17.jar exist.

> Caught java.nio.file.NoSuchFileException (/home/runner/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.12.17/.scala-compiler-2.12.17.jar.part -> /home/runner/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.12.17/scala-compiler-2.12.17.jar)

Maybe this failed because of concurrent downloads by Coursier. Just a random guess.

**Comment by mzuehlke** [comment]
The log from @EwoutH shows he was using scala-steward version [v0.17.0](https://github.com/scala-steward-org/scala-steward/tree/v0.17.0), 
which uses  ["io.get-coursier" %% "coursier" % "2.1.0-RC3" ](https://github.com/scala-steward-org/scala-steward/blob/v0.17.0/project/Dependencies.scala#L17)
The concurrent downloads bug got fixed in v2.1.0-RC2 https://github.com/coursier/coursier/pull/2591

**Comment by fthomas** [comment]
<details>
<summary>Here is the complete stack trace is.</summary>
<pre>
  Error:  scalafix.interfaces.ScalafixException: Failed to fetch [Dependency(Module(ch.epfl.scala, scalafix-cli_2.12.17), 0.10.4, configuration=runtime)]from [ApiRepo(IvyRepository(Pattern(List(Const(file:/home/runner/.ivy2/local/), Var(organisation), Const(/), Var(module), Const(/), Opt(List(Const(scala_), Var(scalaVersion), Const(/))), Opt(List(Const(sbt_), Var(sbtVersion), Const(/))), Var(revision), Const(/), Var(type), Const(s/), Var(artifact), Opt(List(Const(-), Var(classifier))), Const(.), Var(ext))), None, None, true, true, true, true, None, true)), ApiRepo(MavenRepository(https://repo1.maven.org/maven2, None, None, true, true)), MavenRepository(https://oss.sonatype.org/content/repositories/public)]
  Error:  	at scalafix.internal.interfaces.ScalafixCoursier.fetch(ScalafixCoursier.java:30)
  Error:  	at scalafix.internal.interfaces.ScalafixCoursier.scalafixCliJars(ScalafixCoursier.java:55)
  Error:  	at scalafix.interfaces.Scalafix.fetchAndClassloadInstance(Scalafix.java:139)
  Error:  	at scalafix.internal.sbt.ScalafixInterface$.$anonfun$fromToolClasspath$1(ScalafixInterface.scala:136)
  Error:  	at scala.util.Try$.apply(Try.scala:213)
  Error:  	at scalafix.internal.sbt.ScalafixInterface$LazyValue._value$lzycompute(ScalafixInterface.scala:116)
  Error:  	at scalafix.internal.sbt.ScalafixInterface$LazyValue._value(ScalafixInterface.scala:116)
  Error:  	at scalafix.internal.sbt.ScalafixInterface$LazyValue.apply(ScalafixInterface.scala:117)
  Error:  	at scalafix.sbt.ScalafixPlugin$.$anonfun$scalafixArgsFromShell$8(ScalafixPlugin.scala:258)
  Error:  	at scalafix.internal.sbt.BlockingCache$$anon$1.apply(BlockingCache.scala:19)
  Error:  	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
  Error:  	at java.base/java.util.Collections$SynchronizedMap.computeIfAbsent(Collections.java:2760)
  Error:  	at scalafix.internal.sbt.BlockingCache.getOrElseUpdate(BlockingCache.scala:18)
  Error:  	at scalafix.sbt.ScalafixPlugin$.scalafixArgsFromShell(ScalafixPlugin.scala:258)
  Error:  	at scalafix.sbt.ScalafixPlugin$.$anonfun$scalafixTask$1(ScalafixPlugin.scala:350)
  Error:  	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
  Error:  	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
  Error:  	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
  Error:  	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
  Error:  	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
  Error:  	at sbt.Execute.work(Execute.scala:290)
  Error:  	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
  Error:  	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
  Error:  	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
  Error:  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  Error:  	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
  Error:  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  Error:  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  Error:  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  Error:  	at java.base/java.lang.Thread.run(Thread.java:833)
</pre>
</details>

It hints that we need to have look at the Coursier version used by Scalafix which is [2.0.0-RC5-6](https://github.com/scalacenter/scalafix/blob/v0.10.4/project/Dependencies.scala#L24) in Scalafix 0.10.4. Maybe a new Scalafix version with the latest Coursier would fix this.

/cc @bjaglin

**Comment by bjaglin** [comment]
Given the stack trace, the relevant coursier version here is the one shaded into [coursier-interface 1.0.8](https://github.com/scalacenter/scalafix/blob/a540a64b031e5b4e4cea8499925f38fb3bb01714/project/Dependencies.scala#L25), so [coursier 2.1.0-M6-28-gbad85693f](https://github.com/coursier/interface/blob/bb59b677c540cf96a8811e38fc187990f1c0546c/build.sbt#L170-L178).

The first version of coursier-interface bringing the fix mentioned below seems to be [1.0.12](https://github.com/coursier/interface/releases/tag/v1.0.12), for which the upgrade in scalafix/sbt-scalafix is [not trivial](https://github.com/scalacenter/scalafix/pull/1718#issuecomment-1369225217) (it does require some further verification at least).

Until this is sorted out, and to confirm that the coursier fix works, one could force a more recent version of coursier-interface, that should evict the one from the sbt-scalafix version that scala-steward brings.
```
$ cs resolve --what-depends-on io.get-coursier:interface --sbt-version 1.0 --sbt-plugin "ch.epfl.scala:sbt-scalafix:0.10.4" 
  Result:
└─ io.get-coursier:interface:1.0.8
   ├─ ch.epfl.scala:sbt-scalafix;sbtVersion=1.0;scalaVersion=2.12:0.10.4
   └─ ch.epfl.scala:scalafix-interfaces:0.10.4
      └─ ch.epfl.scala:sbt-scalafix;sbtVersion=1.0;scalaVersion=2.12:0.10.4
```
```
// project/plugins.sbt
libraryDependencies += "io.get-coursier" % "interface" % "1.0.13" // to evict 1.0.8 that sbt-scalafix brings
```

**Comment by bjaglin** [comment]
For the record, [sbt-scalafix 0.10.4+38-b5c44057-SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/ch/epfl/scala/sbt-scalafix_2.12_1.0/0.10.4+38-b5c44057-SNAPSHOT/) uses coursier-interface 1.0.15, which shades coursier 2.1.0. I'll cut a release within a couple of weeks.

**Comment by fthomas** [comment]
Closing because this should be working now.
