### ISSUE TITLE
I want to refer to the GitHub repository of Google Cloud SDK.

### ISSUE THREAD

**Issue by Javakky-pxv** [scala-steward-org/scala-steward#2789]
Most Google Cloud Java SDKs are maintained in repositories linked from the following GitHub repositories.
https://github.com/googleapis/google-cloud-java

However, this URL is not tied to the description generated by Scala Steward, probably because the ArtifactId is different from the repository name.

1. How does Scala Steward identify the GitHub URL?
2. Is there anything I can do to make Scala Steward aware of the various GCloud SDKs?

**Comment by exoego** [comment]
1. Scala Steward tries to find the source repo (mostly in GitHub) by mapping `artifactId` to `URL`. The ID-to-URL map is created here. https://github.com/scala-steward-org/scala-steward/blob/d87ab874d722295a1cb5570ee3dda2a201bf5d70/modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala#L206-L210 URL is fetched from metadata in pom.xml. If URL is not in metadata, unfortunately, Scala Steward can not link right now.
2. Scala Steward tries to find CHANGELOG and/or RELEASENOTES from the source repository. https://github.com/scala-steward-org/scala-steward/blob/d87ab874d722295a1cb5570ee3dda2a201bf5d70/modules/core/src/main/scala/org/scalasteward/core/vcs/VCSExtraAlg.scala#L47-L54 If URL returns error (which means not-found), Scala Steward does not create links.

**Comment by fthomas** [comment]
If I understand this issue correctly, various googleapis have broken URLs in their POMs which need to be corrected in the googleapis repos. I think there is nothing Scala Steward can or should do in such cases and we can close this issue. Am I missing something?
