### ISSUE TITLE
Your CPU is probably starving... logged

### ISSUE THREAD

**Issue by francisdb** [scala-steward-org/scala-steward#2790]
We are seeing below errors when running scala steward on github actions. Mainly at the start of the run, I guess it improves with jvm warmup.

```
  Warning:  Your CPU is probably starving. Consider increasing the granularity
  Error: of your delays or adding more cedes. This may also be a sign that you are
  Error: unintentionally running blocking I/O operations (such as File or InetAddress)
  Error: without the blocking combinator.
```

This is coming from cats-effect
https://github.com/typelevel/cats-effect/blob/72fc25482fe01413a598432c522cb92dc3dcff3f/core/shared/src/main/scala/cats/effect/CpuStarvationCheck.scala#L43

Just wanted to mention this, if this is a non-issue feel free to close.

**Comment by exoego** [comment]
Thanks.
Let's keep this open. We may tweak cats-effect for better resource handling.

**Comment by armanbilge** [comment]
We've also gotten reports of this warning with applications using the http4s okhttp client backend, which uses blocking. Note that even when blocking ops are handled correctly, having a large number of blocking threads on a low-core (virtual) machine can create kernel contention and cause starvation.

**Comment by armanbilge** [comment]
Hopefully https://github.com/scala-steward-org/scala-steward/pull/2888 has helped address starvation issues as well.

**Comment by mmatys-demyst** [comment]
```
2025-04-22T08:56:46.438Z [WARNING] Your app's responsiveness to a new asynchronous event (such as a new connection, an upstream response, or a timer) was in excess of 100 milliseconds. Your CPU is probably starving. Consider increasing the granularity of your delays or adding more cedes. This may also be a sign that you are unintentionally running blocking I/O operations (such as File or InetAddress) without the blocking combinator.
```
just observed today while running Scala Steward via GitHub actions.
