### ISSUE TITLE
JSON parsing error when decoding pull_requests.json

### ISSUE THREAD

**Issue by alifirat** [scala-steward-org/scala-steward#2802]
Hi, 

I've decided to give a try to the new features available on the 0.16.0, especially the grouping one. The problem is that I see some errors, when deserializing the `pull_requests.json` which is an internal file to the Steward workspace. 

Below is the JSON that Steward tried to parse: 
```json
{
  "https://github.com/ContentSquare/de_steward-test-repository/pull/69" : {
    "baseSha1" : "2b7603f40dcfb122e84e65f19905be8c9c660d36",
    "update" : {
      "Grouped" : {
        "name" : "all",
        "title" : null,
        "updates" : [
          {
            "crossDependency" : [
              {
                "groupId" : "org.scala-lang",
                "artifactId" : {
                  "name" : "scala-library",
                  "maybeCrossName" : null
                },
                "version" : "2.12.17",
                "sbtVersion" : null,
                "scalaVersion" : null,
                "configurations" : "provided"
              }
            ],
            "newerVersions" : [
              "2.13.10"
            ],
            "newerGroupId" : null,
            "newerArtifactId" : null
          }
        ]
      }
    },
    "state" : "closed",
    "entryCreatedAt" : 1669725032488,
    "number" : 69,
    "updateBranch" : "update/all"
  }
}
```

And the error says: 
```
ERROR Failed to parse or decode JSON from /opt/docker/workspace/store/pull_requests/v2/github/ContentSquare/de_steward-test-repository/pull_requests.json
io.circe.DecodingFailure$DecodingFailureImpl: Missing required field: DownField(Single),DownArray,DownField(updates),DownField(Grouped),DownField(update),DownField(https://github.com/ContentSquare/de_steward-test-repository/pull/69)
```

Since the internal looks local to Steward, I'm not sure how can I do more on my side. I've already cleanup my workspace and the errors still occurs. Can you please help?

**Comment by alejandrohdezma** [comment]
Hey @alifirat, do you have a link to the execution? Or could you copy/paste the logs? Thanks!

**Comment by alifirat** [comment]
Hey @alejandrohdezma, thanks for answering!
Do you have the logs in a debug mode or the full logs with the LEVEL info is enough?

**Comment by alejandrohdezma** [comment]
If you could have the debug logs that would be great :)

**Comment by alejandrohdezma** [comment]
This has been fixed on version [0.16.1](https://github.com/scala-steward-org/scala-steward/releases/tag/v0.16.1)

**Comment by alejandrohdezma** [comment]
`scala-steward-action` has also been updated to include this change on v2

**Comment by alifirat** [comment]
hey @alejandrohdezma 
I would like to have your attention on this feature. When I set the following properties : 
```properties
pullRequests.grouping = [
    { name = "all", "filter" = [{"group" = "*"}]},
    { name = "patches", "filter" = [{"version" = "patch"}] }
]
``` 
I've interpret like `I want only the PRs that bump the patch version into a single PR`,  am I right? 

Because I get the following PR that bumps: 
- `cats-core` : from 2.3.0 to 2.9.0 while I was expected a bump to 2.3.1 
- `circe-core`: from 0.13.0 to 0.14.1 while I was expected no PR since there is no major version availables after the 0.13.0.

**Comment by alejandrohdezma** [comment]
Hey @alifirat, those are different things.

First of all in the example you're showing, the groups you are creating are:

- One that says, put every update on this group.
- One that says, put every patch update on this group.

So, [as stated in the docs](https://github.com/scala-steward-org/scala-steward/blob/main/docs/repo-specific-configuration.md):

> Updates will be placed in the first group with which they match, starting from the first in the array.

So since your first filter "swallows" everything, every update is going to fall into that group.

On the other hand, `grouping` here is a pull-request configuration, so it just affects how pull-requests are created, no how updates are find. For that you have `update.allow` or `update.ignore`.

**Comment by alifirat** [comment]
Hey @alejandrohdezma 
Thank you for pointing me the documentation part I've missed, now I understand!

Is it possible with the `grouping` settings to implement a kind of `AND` like my use case: I want only to update the patch version **AND** group them into a single PR.

**Comment by alejandrohdezma** [comment]
If you want for all patch updates to fall in the same PR, you just need to change the order in your list:

```conf
pullRequests.grouping = [
    { name = "patches", "filter" = [{"version" = "patch"}] },
    { name = "all", "filter" = [{"group" = "*"}]}
]
```

For limiting the scope of the updates, you'll need to use `update.pin` or `update.ignore`

**Comment by alifirat** [comment]
@alejandrohdezma super powerful feature, a lot of people from my team will be happy :-D

**Comment by alejandrohdezma** [comment]
Yeah, both are accepted since it is using [HOCON](https://github.com/lightbend/config/blob/main/HOCON.md#unquoted-strings).
