### ISSUE TITLE
Use a more principled approach for replacing version numbers in files

### ISSUE THREAD

**Issue by fthomas** [scala-steward-org/scala-steward#2811]
One of the oldest and opaque parts of Scala Steward is [`UpdateHeuristic`](https://github.com/scala-steward-org/scala-steward/blob/48b8d97b82a1a082b7a6960d3f717b1e7dc3fed0/modules/core/src/main/scala/org/scalasteward/core/edit/UpdateHeuristic.scala). It is responsible for locating the correct version number in files and for updating them. It is hard to understand and to extend because it does three things at the same time per file:
 1. locating the positions of the old version
 2. deciding which version number is the correct one (i.e. corresponds to the artifacts that are updated)
 3. replacing the old version number with the new one

I would like to retire `UpdateHeuristic` with an approach where the three steps above are completely separated and done sequentially. I envision that it works more like this:
1. locate all positions of the old version number in all files and classify them (e.g. if they are part of a sbt ModuleID, a Maven dependency definition, or the value of a `val`)
2. look at all of the above version positions and decide which one of those should be updated
3. replace the version in the files and positions selected by step 2

I think the reason why this is easier to understand and to extend is that we would have in step 2 all positions of the old version numbers at hand and then can make an informed decision based on the classification that happened in step 1.

I'm working on a prototype of this approach in https://github.com/scala-steward-org/scala-steward/compare/wip/version-position and it looks promising so far. For example, problems as described in https://github.com/scala-steward-org/scala-steward/issues/1184 are easy to fix since matching the `val` used in the ModuleID with the `val` used for the version number is easy. This approach would also eliminate current limitations of `UpdateHeurisitc` like multiline `val`s or Maven dependency definitions where groupId, artifactId, and version are on different lines.

Comments about this approach or other ideas how to do this even better are very welcome!

**Comment by fthomas** [comment]
The branch mentioned above is currently able to fix the following issues: #1184, #1699, #1977, #2099, #2664, #2675

**Comment by alejandrohdezma** [comment]
I took a quick look at the new approach and it looks solid (and way more extensible than the old one). I have a question I've always wondered about Steward on this matter, is there a reason for not using something like Scalafix for applying the updates? It should be able to do most of the parsing for us

**Comment by fthomas** [comment]
> I've always wondered about Steward on this matter, is there a reason for not using something like Scalafix for applying the updates? It should be able to do most of the parsing for us

There is an ancient issue about that (https://github.com/scala-steward-org/scala-steward/issues/103) and I think the arguments given in https://github.com/scala-steward-org/scala-steward/issues/103#issuecomment-711080595 are still valid. Maybe Scalafix/Scalameta could be a part of the parsing and finding version numbers task. It would be much more reliable than the regexes we currently have and would probably also work in "complicated" cases like shown in #2600.

**Comment by fthomas** [comment]
I guess it would be straightforward to use the [Scalameta parser](https://scalameta.org/docs/trees/guide.html#from-strings) in [`VersionScanner`](https://github.com/scala-steward-org/scala-steward/compare/wip/version-position#diff-20dfa2d35508fcbb67ba53c32f09e1e987733eb156813b36bd2752c4c092438c) in addition to what is currently there to find more accurate `VersionPosition`s which would then result in more accurate version bumps.
