### ISSUE TITLE
Incorrect pr sent in for an artifact found in test code

### ISSUE THREAD

**Issue by ckipp01** [scala-steward-org/scala-steward#2819]
I have a small Maven project that as part of the tests checks to see what jars exist in a module. Steward today sent in a PR to update one of those jar versions even though it's not defined anywhere that I'm using this. Plus this is just code inside of one of my Scala files that I don't believe Steward should be touching unless it was somehow linked to my build definition. You can see the example of the pull request here in [scalacenter/bloop-maven-plugin](https://github.com/scalacenter/bloop-maven-plugin/pull/33).

- For context the job that created the pr can be found [here](https://github.com/scalacenter/steward/actions/runs/3681007721/jobs/6227224990). 
- Steward version - `v0.16.1`

**Comment by exoego** [comment]
Is the Steward instance running with default config or scala center specific config?

**Comment by fthomas** [comment]
Scala Steward uses `mvn dependency:list` to retrieve the dependencies from Maven and that one outputs for bloop-maven-plugin:
```
...
[INFO]    org.scala-sbt:io_2.13:jar:1.8.0:compile
[INFO]    junit:junit:jar:4.13:test
[INFO]    aopalliance:aopalliance:jar:1.0:provided
...
```
It therefore thinks that it depends on junit and tried to update it.

**Comment by ckipp01** [comment]
Huh, odd. I'm not familiar enough with maven to offer any good insight here, but I find it odd that it even show that. Since I do rely on `com.github.sbt:junit-interface`, but that actually brings in a different version of `junit`:

```
❯ cs resolve com.github.sbt:junit-interface:0.13.3
com.github.sbt:junit-interface:0.13.3:default
junit:junit:4.13.2:default
org.hamcrest:hamcrest-core:1.3:default
org.scala-sbt:test-interface:1.0:default
```

So it must be transitive of something, but I wonder how we can filter that out.

**Comment by fthomas** [comment]
Maybe we could use `mvn dependency:tree` and only collect the dependencies with depth 1:
```
...
[INFO] +- org.apache.maven.shared:maven-verifier:jar:1.7.2:test
[INFO] |  +- junit:junit:jar:4.13:test
[INFO] |  \- org.hamcrest:hamcrest-core:jar:2.2:test
[INFO] |     \- org.hamcrest:hamcrest:jar:2.2:test
[INFO] \- com.github.sbt:junit-interface:jar:0.13.3:test
[INFO]    \- org.scala-sbt:test-interface:jar:1.0:test

```
