### ISSUE TITLE
StewardPlugin.scala cannot be loaded by sbt < 1.3.0

### ISSUE THREAD

**Issue by fthomas** [scala-steward-org/scala-steward#2847]
Since https://github.com/scala-steward-org/scala-steward/pull/2533 `StewardPlugin.scala` cannot be loaded by sbt versions older than 1.3.0 (i.e sbt without Coursier integration) as can be seen in com-lihaoyi/scalatags which still uses sbt 1.2.8:
```
[info] 2022-12-21 20:06:37,126 INFO  ──────────── Steward com-lihaoyi/scalatags ────────────
[info] 2022-12-21 20:06:37,127 INFO  Check cache of com-lihaoyi/scalatags
[info] 2022-12-21 20:06:38,065 INFO  Clone scala-steward/scalatags
[info] 2022-12-21 20:06:39,254 INFO  Synchronize with com-lihaoyi/scalatags
[info] 2022-12-21 20:06:40,215 INFO  Refresh cache of com-lihaoyi/scalatags
[info] 2022-12-21 20:07:01,284 ERROR Steward com-lihaoyi/scalatags failed
[info] java.io.IOException: 'sbt -Dsbt.color=false -Dsbt.log.noformat=true -Dsbt.supershell=false ;+ stewardDependencies;reload plugins;stewardDependencies' exited with code 1
[info] [info] Loading global plugins from /home/frank/.sbt/1.0/plugins
[info] [info] Updating ProjectRef(uri("file:/home/frank/.sbt/1.0/plugins/"), "global-plugins")...
[info] [info] Done updating.
[info] [info] Compiling 1 Scala source to /home/frank/.sbt/1.0/plugins/target/scala-2.12/sbt-1.0/classes ...
[info] [error] /home/frank/.sbt/1.0/plugins/StewardPlugin.scala:67:15: not found: value csrConfiguration
[info] [error]               csrConfiguration.value.authenticationByRepositoryId.toList
[info] [error]               ^
[info] [error] /home/frank/.sbt/1.0/plugins/StewardPlugin.scala:69:56: value headers is not a member of Any
[info] [error]             (headerKey, headerValue) <- authentication.headers
[info] [error]                                                        ^
[info] [error] /home/frank/.sbt/1.0/plugins/StewardPlugin.scala:70:35: type mismatch;
[info] [error]  found   : Any
[info] [error]  required: String
[info] [error]           } yield Resolver.Header(headerKey, headerValue)
[info] [error]                                   ^
[info] [error] /home/frank/.sbt/1.0/plugins/StewardPlugin.scala:70:46: type mismatch;
[info] [error]  found   : Any
[info] [error]  required: String
[info] [error]           } yield Resolver.Header(headerKey, headerValue)
[info] [error]                                              ^
[info] [error] four errors found
[info] [error] (Compile / compileIncremental) Compilation failed
[info] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?
```
It fails to load the build because the [`csrConfiguration`](https://github.com/scala-steward-org/scala-steward/blob/3f7dfa96746a69b2935fd014b326f34afd9002d3/modules/sbt-plugin/src/main/scala/org/scalasteward/sbt/plugin/StewardPlugin.scala#L67) task is not available in those old sbt versions.

**Comment by julienrf** [comment]
Did you encounter similar issues in the past? Is it possible to inject parts of the plugin only if we detect that the sbt version supports it?

**Comment by julienrf** [comment]
Oh, I see now that in #2848 you basically say that sbt <1.3.0 is not anymore supported?

**Comment by fthomas** [comment]
I don't think we should merge #2848 as is. I would prefer using different sbt plugins based on the used sbt version. That should be possible without too much effort.

**Comment by mzuehlke** [comment]
Can we just load the `csrConfiguration` stetting keys dynamically like we are doing if for `scalafixDependencies` https://github.com/scala-steward-org/scala-steward/blob/b483de7d73a5c92917e4bcb81ca5d5736c58b3ad/modules/sbt-plugin/src/main/scala/org/scalasteward/sbt/plugin/StewardPlugin.scala#L93-L102

**Comment by fthomas** [comment]
I think that this does not work here because the type of `csrConfiguration` is `CoursierConfiguration`. If we write `SettingKey[CoursierConfiguration]("csrConfiguration").?` sbt still fails to load this because older sbt versions do not know `CoursierConfiguration`.

**Comment by fthomas** [comment]
Maybe this can be circumvented with some clever type unsafety.

**Comment by fthomas** [comment]
My assumption that the plugin requires at least 1.3.0 was not correct. 1.3.11 is actually the oldest sbt version that can load it.
