### ISSUE TITLE
Specify custom preRelease identifier

### ISSUE THREAD

**Issue by alexklibisz** [scala-steward-org/scala-steward#2866]
I have a library that uses `"x.y.z"` for stable releases, and  `"x.y.z+FEAT.<some other metadata>" ` for pre-releases. 

It looks like FEAT is not one of the identifiers known by [Version.Component.Alpha](https://github.com/scala-steward-org/scala-steward/blob/7e312bd5eb80edddc58c6aeb5bfb589a8d1d8708/modules/core/src/main/scala/org/scalasteward/core/data/Version.scala#L163-L176).

So we get scala-steward PRs for the pre-releases of this library.

Is there any way to tell scala-steward that FEAT is a pre-release identifier?

If not, maybe I can make a PR for this? I see a couple options:

* Just add "FEAT" as one of the hard-coded identifiers. It seems relatively common.
* Add a repo-specific configuration that's just a list of snapshot.

**Comment by fthomas** [comment]
I don't mind adding `FEAT` to the hard-coded list of identifiers.

**Comment by alexklibisz** [comment]
Took a first pass here: https://github.com/scala-steward-org/scala-steward/pull/2870

**Comment by fthomas** [comment]
Fixed by #2870.

**Comment by alexklibisz** [comment]
Thanks for the quick review and merge. Is there an expected turn-around time for this to land in a release?
