### ISSUE TITLE
http4s-okhttp-client is currently unmaintained

### ISSUE THREAD

**Issue by armanbilge** [scala-steward-org/scala-steward#2887]
See https://github.com/http4s/http4s/discussions/6908. Cross-posting for visibility if anyone wants to volunteer in the name of the steward 😁 

However, if possible I think it would be good to switch to another client. Unfortunately the http4s integration relies on blocking and is a possible cause of the new "CPU starvation" warning. I also hear oft-repeated anecdotes about okhttp leaking.

I understand from https://github.com/scala-steward-org/scala-steward/issues/888 there is a requirement for proxy support. I think that leaves the http4s-jdk-http-client as the only other candidate. It's a good integration I help maintain, so I can vouch.

https://github.com/http4s/http4s-jdk-http-client/

**Comment by fthomas** [comment]
I'm fine with switching to http4s-jdk-http-client. Since we recently dropped Java 8 support, I don't see a problem in doing so.

**Comment by armanbilge** [comment]
Actually I forgot: ftr http4s-netty-client also has proxy support. But it's a bit heavy-weight 😅

**Comment by TonioGela** [comment]
I can take of this migration if you like ✋

**Comment by fthomas** [comment]
That would be great, @TonioGela!
