### ISSUE TITLE
Include ${artifactName}, ${currentVersion}, ${nextVersion} in the pullRequests.grouping title

### ISSUE THREAD

**Issue by alexklibisz** [scala-steward-org/scala-steward#2902]
I see that we can already interpolate variables into the commit message, via [repo-specific configuration](https://github.com/scala-steward-org/scala-steward/blob/main/docs/repo-specific-configuration.md):

```
commits.message = "Update ${artifactName} from ${currentVersion} to ${nextVersion}"
```

Would it make sense to also support something similar in the pullRequests.grouping title property?

```
pullRequests.grouping = [
  { ... title = "${updateSummary} }
]
```

Here's my specific usecase, and the reason for asking this question:

I have a group in `pullRequests.grouping` that updates all dependencies in `"com.foo"`:

```
pulRequests.grouping  = [
  { name = "foo-libraries", title = "Foo Library Updates", "filter" = [{group = "com.foo"}] }
]
```

I choose to group all "com.foo" updates together because it would otherwise lead to too many PRs and possible merge conflicts.

However, I'd also like to be able to include the updates that were made in the `title` property. 

Something like `title = "Update: ${updates}"`, would create a PR with a title like "Update com.foo:library-1 to 1.2.3, com.foo:library-2 to 2.3.4".

Why include it in the title? The PR title is commonly used as the final commit message, whether by squash+merge or rebase+merge, so I'd like to have the versions included in the commit message.

If this makes sense as a feature, I can take a pass at implementing.

**Comment by alejandrohdezma** [comment]
Hey @alexklibisz I see why adding this for small updates would make sense, but it will be completely disastrous for big updates, since PR titles are truncated then. Once suggestion I would make is to (using GitHub Actions) include the PR body in the commit message when merging the PR.

**Comment by alexklibisz** [comment]
Yeah, this would get ugly for large updates. Hmm. I'll think about the Actions approach. I might also just split up the PRs and see how bad the conflicts get. Will close for now and re-open if I think of any other solution to the issue I described.
