### ISSUE TITLE
How to configure tests to print warning logs

### ISSUE THREAD

**Issue by alexklibisz** [scala-steward-org/scala-steward#2903]
I've encountered another "Unable to bump version" that seems to actually be a false positive, i.e., it actually _was_ able to bump that version. I'm trying to write a test in RewriteTest to reproduce the issue, but I'm not seeing the logs. Is there anything special I need to configure in the build in order to see the warning logs?

**Comment by fthomas** [comment]
Put a `state.trace.foreach(println)` below this line to see the logs:
https://github.com/scala-steward-org/scala-steward/blob/96303ba5adc878bc92f4e4a2efcf5123eafbc35e/modules/core/src/test/scala/org/scalasteward/core/edit/RewriteTest.scala#L926

**Comment by mzuehlke** [comment]
Thank you, I had the same issue the other day and failed to get anything logged.
I tried to modify the `logback.xml` with no success.

Maybe this is worth an entry in the FAQ ?

**Comment by fthomas** [comment]
Yeah, as soon as [`MockState`](https://github.com/scala-steward-org/scala-steward/blob/96303ba5adc878bc92f4e4a2efcf5123eafbc35e/modules/core/src/test/scala/org/scalasteward/core/mock/MockState.scala) is involved everything is logged via the [`MockLogger`](https://github.com/scala-steward-org/scala-steward/blob/96303ba5adc878bc92f4e4a2efcf5123eafbc35e/modules/core/src/test/scala/org/scalasteward/core/mock/MockLogger.scala) which just appends a log entry to the `MockState#trace`. Logback is not involved in these cases.

> Maybe this is worth an entry in the FAQ ?

It is a good idea to document this. The FAQ is fine or maybe this would be a good opportunity to start a guide for contributors?

**Comment by alexklibisz** [comment]
Thanks, confirmed this works for me.

Agreed this makes more sense in a contributor guide than in user-facing docs, maybe start a "How-to" section in contributing.md?. I can take a quick first pass.

**Comment by alexklibisz** [comment]
Closing as this worked for me. Thanks!
