### ISSUE TITLE
`.scalafmt.conf` is only updated in the root directory

### ISSUE THREAD

**Issue by fthomas** [scala-steward-org/scala-steward#2947]
Scalafmt updates only change the `.scalafmt.conf` in the root directory since #2816.

before #2816:
https://github.com/fthomas/base.g8/pull/151/files

since #2816:
https://github.com/fthomas/base.g8/pull/160/files

We should restore the previous behavior and update all `.scalafmt.conf` files that use the same version.

**Comment by yaroot** [comment]
Also it requires the `.scalafmt.conf` to be in the root directory, otherwise reformat will fail.
