### ISSUE TITLE
do not check files/folders that are .gitignored

### ISSUE THREAD

**Issue by daddykotex** [scala-steward-org/scala-steward#2979]
We're having some weird behaviour on our local Scala Steward instance and I started looking into it. Originally, the problem is that we're getting pull requests with invalid changes in them (I'll open another issue for that). But when investigating, I was trying to understand the codebase a little bit better and realized the following: Scala Steward looks into a bunch of files that are code-generated.

We're using smithy4s on our project and before compilation, we code generate Scala files into `target/scala/src_managed`. Scala steward will read those files and try to come up with `VersionPosition` or `ModulePosition`.

My suggestion is that we ignore and file/folder that is gitignored.

What do you think? Would you be open to review a PR that implement this?

**Comment by fthomas** [comment]
> My suggestion is that we ignore and file/folder that is gitignored.

Sounds good to me. This is somewhat related to #2942 and I think it is a good default if Scala Steward also ignores files that are .gitignored.

**Comment by daddykotex** [comment]
Great, would you be open if I included `https://github.com/arturopala/gitignore` ?

**Comment by fthomas** [comment]
As much more efficient alternative to [`git check-ignore`](https://git-scm.com/docs/git-check-ignore)? Yeah, sure.

**Comment by daddykotex** [comment]
I don't mind using `git-check-ignore` before adding, because I guess it will be more accurate and evolve in pair with `git-add`, but to filter out files we want to ignore, I definitely think that an approach that avoids an external process will be faster.

**Comment by daddykotex** [comment]
First PR for #2942 is open: https://github.com/scala-steward-org/scala-steward/pull/2982
