### ISSUE TITLE
Why is scala-steward never visiting our repo?

### ISSUE THREAD

**Issue by mkurz** [scala-steward-org/scala-steward#2993]
* Repo: https://github.com/playframework/play-samples
* Entry in your `repos-github.md`: https://github.com/VirtusLab/scala-steward-repos/blob/cd2fd57f5aef655db13128de1300341eb8bc8e33/repos-github.md?plain=1#L926
* We set up following `.scala-steward.conf` because there are many different sbt projects in that repo (there is no `build.sbt` in the root):  https://github.com/playframework/play-samples/blob/2.9.x/.scala-steward.conf
* scala-steward was never visiting: https://github.com/playframework/play-samples/pulls?q=author%3Ascala-steward+

Is there a problem with our config? Is there a log somewhere what's going on?
Thanks!

**Comment by fthomas** [comment]
Please open this issue in https://github.com/VirtusLab/scala-steward-repos. VirtusLab is now operating the public Scala Steward instances.

**Comment by mkurz** [comment]
Alright, thanks!

**Comment by mkurz** [comment]
For the record: https://github.com/VirtusLab/scala-steward-repos/issues/179
