### ISSUE TITLE
Run Scala CLI with `--power`

### ISSUE THREAD

**Issue by fthomas** [scala-steward-org/scala-steward#2998]
From https://github.com/typelevel/steward/actions/runs/4295085058/jobs/7485006840:
```
  2023-02-28 16:24:57,485 ERROR Steward typelevel/cats-effect:series/3.x failed
  org.scalasteward.core.io.process$ProcessFailedException: '"SBT_OPTS=-Xmx2048m -Xss8m -XX:MaxMetaspaceSize=512m" scala-cli export --sbt --output tmp-sbt-build-for-scala-steward /home/runner/scala-steward/workspace/repos/typelevel/cats-effect' exited with code 1.
  Unrecognized argument: `--sbt` option is not supported.
  Please run it with the `--power` flag or turn this flag on globally by running `config power true`.
```

Scala CLI 0.2.0 now requires to run the `export` command with `--power`. Therefore https://github.com/scala-steward-org/scala-steward/blob/v0.22.0/modules/core/src/main/scala/org/scalasteward/core/buildtool/scalacli/ScalaCliAlg.scala#L54 needs to be updated to include `--power` like this:
```
scala-cli --power export --sbt --output ...
```

**Comment by alejandrohdezma** [comment]
Yeah, that's easier I believe if it's only used there, yeah 😊
