### ISSUE TITLE
groupings and frequency

### ISSUE THREAD

**Issue by nicl** [scala-steward-org/scala-steward#3096]
Hi, really like the grouping feature to batch updates into fewer PRs. However, there is a lack of clarity perhaps in how this should integrate with pullRequest.frequency settings, specifically those set within `dependencyOverrides`.

To illustrate, here is an example (real) configuration:

```
pullRequests.grouping = [
  { name = "aws", "title" = "AWS dependency updates", "filter" = [{"group" = "software.amazon.awssdk"}, {"group" = "com.amazonaws"}] },
  { name = "non_aws", "title" = "Non-AWS dependency updates", "filter" = [{"group" = "*"}] }
]

# Only limit frequency on dependencies which automatically release updates as frequently
# as daily, without those dependencies having meaningful security value.
dependencyOverrides = [
  {
    dependency = { groupId = "com.amazonaws" },
    pullRequests = { frequency = "7 days" }
  },
  {
    dependency = { groupId = "software.amazon.awssdk" },
    pullRequests = { frequency = "30 days" }
  },
  {
    dependency = { groupId = "com.google.apis" },
    pullRequests = { frequency = "30 days" }
   }
]
```

This was created with the intention of limiting certain updates to reduce noise, while also grouping things as well.

At the moment this doesn't work - grouping PRs are opened daily (we run ss daily) without regard for the frequency settings in the dependencyOverrides.

I suspect this is our fault and that the intended behaviour is that these features should not overlap. But it would be good to clarify this. Once confirmed, happy to raise a PR to make clear in the docs how the two features relate (or do not).

To take this further, below are some options for how things *could* work here if we wanted them to...

## Option 1 - dependencyOverride settings are used for grouping PRs

I.e. in the above example, the `aws` grouping would only raise a PR every 30 days.

## Option 2 - dependencyOverride settings are ignored for grouping PRs

This is I believe the status quo - and so PRs are raised at the default frequency 'asap'.

## Option 3 - custom frequency per grouping

Option 1 doesn't make a lot of sense (it could be argued) as grouping filters are much richer and nuanced than dependencyOverrides, which allows just matching by `groupId`. Instead, we could support `frequency` *on* groupings. E..g

```
pullRequests.grouping = [
  { name = "aws", "title" = "AWS dependency updates", "filter" = [{"group" = "software.amazon.awssdk"}, {"group" = "com.amazonaws"}], frequency = "30 days" },
  { name = "non_aws", "title" = "Non-AWS dependency updates", "filter" = [{"group" = "*"}], frequency = "7 days" }
]
```

(Above, we limiit `aws` group PRs to every 30 days, and `non_aws` to every 7 days.)

This is perhaps clearer about what is going on. Again, any `dependencyOverride` settings would be ignored.

## Some scenarios - to illustrate

Stepping back, and thinking about the needs of different people, we might have the following scenarios:

1) Grouping simply to reduce the number of PRs

Can be achieved atm by e.g.:

```
pullRequests.frequency = "7 days"

pullRequests.grouping = [
  { name = "all", "title" = "All dependency updates", "filter" = [{"group" = "*"}] },
]
```

2) Grouping with different frequencies

E.g. to split minor/major from patch and apply the latter more frequency, perhaps with some kind of automerge (handled outside SS):

```
pullRequests.frequency = "7 days"

pullRequests.grouping = [
  { name = "patch", "title" = "Patch dependency updates", "filter" = [{"version" = "patch"}] },
  { name = "minor_major", "title" = "Major/minor dependency updates", "filter" = [{"version" = "minor"}, {"version" = "major"}] },
]
```

Note, it is *not* currently possible (as I understand it) to run these at different frequencies.

**Comment by rtyley** [comment]
Of the different options listed, I think that **Option 1** (_dependencyOverride settings are used for grouping PRs_) is a definite **yes**, they _should_ apply - it's definitely _contrary_ to user expectations that they should specify a dependency frequency and immediately & repeatedly see new PRs raised  for those dependencies. I'm happy to pick up https://github.com/scala-steward-org/scala-steward/pull/3087 and finish that off?

I think Option 3 (_adding `frequency` to `pullRequests.grouping` elements_) could be a reasonable enhancement, but would take a bit more work, and implementing Option 1 - fixing the outstanding bug - should take precedence.
