### ISSUE TITLE
Scala Steward won't update body of PR if new dependency added, or tracked versions changed

### ISSUE THREAD

**Issue by d-g-n** [scala-steward-org/scala-steward#3110]
Hi, I'm not sure if this is a me problem or not, i'm running latest scala steward periodically against a number of repos, my config is as follows:

```
updates.fileExtensions = [".scala", ".sbt", ".sbt.shared", ".sc", ".yml", ".md", ".markdown", ".txt", ".properties"]
updatePullRequests = "always"
pullRequests.grouping = [
  { name = "all", "title" = "[SCALA STEWARD] Dependency updates", "filter" = [{"group" = "*"}] }
]
```

When it initially creates the PR, it's well formed and the raised PR commits line up with the body of the PR: 
![image](https://github.com/scala-steward-org/scala-steward/assets/10690618/b818952c-91de-4282-9cbe-0f6b24dd7e57)
and commits:
![image](https://github.com/scala-steward-org/scala-steward/assets/10690618/b24687a9-7852-43e4-bb61-1f61d2d886a2)

And that works fine, however if the PR is not merged for a while and maybe a new dependency is added, or an existing dependency changes version number, such as here: 
![image](https://github.com/scala-steward-org/scala-steward/assets/10690618/b394113e-98c2-485f-9fb0-85a85df2270d)
I can confirm that it adds the new version as a commit, but it doesn't seem to update the main PR body, it stays the same as pictured above. I also can't see any `edited` flags against the main PR, i can't see anything in the logs to indicate whether or not this is intended behaviour.

Is this intentional, am i missing something or is this a bug?

Also as an aside, another question: when steward is re-ran against a repo with an already open PR using the grouping functionality, even if the version numbers it wants to update to do not change, it will still revert all PR numbers and generate new commits, this works fine and is a non issue when using squash and merge but results in potentially very many commits being added to the PR and is more bloat than required, is this a bug?

For example:
![image](https://github.com/scala-steward-org/scala-steward/assets/10690618/7e3127e2-076f-48f4-86c5-0ee91d506e59)

Is then immediately followed by 
![image](https://github.com/scala-steward-org/scala-steward/assets/10690618/850b2037-e403-4209-bcad-9179f34f3a54)
Where the version numbers of the update are identical, ideally this would only happen when a version number has changed.

Thanks again

**Comment by alejandrohdezma** [comment]
Hey @d-g-n, thank you very much for bringing this to light! I've created #3111 to fix this for GitHub. I need some time to investigate the other forges APIs to implement it for those too, but at least this will create the foundations and ensure it works on GitHub 😊

**Comment by d-g-n** [comment]
Amazing, thanks for putting that together so quickly, the changes look great.
