### ISSUE TITLE
Documentation for proxy configuration

### ISSUE THREAD

**Issue by max5599** [scala-steward-org/scala-steward#3127]
Hello,

I'm using scala steward in to update my projects in a private gitlab.

I'm getting some connection timeout and I'm suspecting that the proxy is not configured properly.

I've tried to set variables like:
```
  variables:
    # change values here, if needed;
    EMAIL: 'me@scala-steward.org'
    LOGIN: 'scalasteward'
    LOG_LEVEL: 'DEBUG'
    http_proxy: 'http://my.proxy.org:8080'
    https_proxy: 'http://my.proxy.org:8080'
    no_proxy: 'localhost,127.0.0.1'
    JAVA_OPTS: '-Dhttp.proxyHost=my.proxy.org -Dhttp.proxyPort=8080 -Dhttp.nonProxyHosts=localhost,127.0.0.1'
```

It seems to work for some connections but not all, for example:
```
DEBUG Failed to check if https://github.com/ exists
java.net.ConnectException: Operation timed out
```

Any idea how to properly configure the proxy? I was not able to find some documentation.

Thanks

**Comment by fthomas** [comment]
Try adding HTTPS proxy settings (`-Dhttps.proxyHost=my.proxy.org -Dhttps.proxyPort=8080`) to `JAVA_OPTS`.

**Comment by max5599** [comment]
Thanks @fthomas it worked! Should it be documented somewhere?

**Comment by mzuehlke** [comment]
> Thanks @fthomas it worked! Should it be documented somewhere?

A PR to add this to `running.md` would be very welcomed 😄
