### ISSUE TITLE
scala-cli updates not getting picked up

### ISSUE THREAD

**Issue by ckipp01** [scala-steward-org/scala-steward#3174]
I have a scala-cli repo that I noticed isn't getting PRs sent in. I'm running the steward action on it and you can see [here](https://github.com/ckipp01/chris-kipp.io/actions/runs/6244185904/job/16950746242#step:5:345) that it finds no updates for skan. (ignore the failure in the other repos, it's a mill issue). However there are updates for this repo. For example upickle is outdated and when you run it with scala-cli you can see this.

**Comment by fthomas** [comment]
I guess it is because of this line https://github.com/scala-steward-org/scala-steward/blob/204176907f7ab2ac5a8be1b4114bedd7cee09404/modules/core/src/main/scala/org/scalasteward/core/buildtool/scalacli/ScalaCliAlg.scala#L46
but skan uses the `//> using dep` syntax.

**Comment by ckipp01** [comment]
> I guess it is because of this line
> 
> https://github.com/scala-steward-org/scala-steward/blob/204176907f7ab2ac5a8be1b4114bedd7cee09404/modules/core/src/main/scala/org/scalasteward/core/buildtool/scalacli/ScalaCliAlg.scala#L46
> 
> 
> but skan uses the `//> using dep` syntax.

Ahh that could be it. I see the documentation is using `dep` now, so I went with that. I noticed that the way that scala-cli is handles is via an sbt export. Now that there is a json export instead, would that be preferable?

**Comment by fthomas** [comment]
> I see the documentation is using `dep` now, so I went with that.

We need to change Scala Steward to look also for `//> using dep`  or `//> using test.dep` instead of just `//> using lib`.

> I noticed that the way that scala-cli is handles is via an sbt export. Now that there is a json export instead, would that be preferable?

Yes, that would be better than using the sbt export. Since it is not related to `ScalaCliAlg#containsBuild`, I would prefer to do it in a separate PR.
