### ISSUE TITLE
Scala Steward run within an org is incorrectly creating PR's against wrong repo

### ISSUE THREAD

**Issue by mdedetrich** [scala-steward-org/scala-steward#3257]
Upstream Apache INFRA ticket: https://issues.apache.org/jira/browse/INFRA-25323

At Pekko which is an Apache Incubator project we are using Scala steward as a Github application within the `apache` org (i.e. following the instructions at https://github.com/scala-steward-org/scala-steward-action#installation) and we are currently experiencing an issue where for some reason when Scala Steward within https://github.com/apache/incubator-pekko-http is using https://github.com/apache/incubator-pekko as a target repository (which is obviously incorrect, it should be using `incubator-pekko-http`).

This can be seen both in the manually run action at https://github.com/apache/incubator-pekko-http/actions/runs/7311242913, i.e.
![image](https://github.com/scala-steward-org/scala-steward/assets/2337269/54abca49-7c51-4cd0-a368-e435b17c0079)
(as you can see its running against incubator-pekko and not incubator-pekko-http) and also in the job log which you can see at https://gist.github.com/mdedetrich/6d7aa3c7802c9f56e2448093984d82bf

Do you have any idea what can be causing this, I can't see anything in the [scala-steward configuration](https://github.com/apache/incubator-pekko-http/blob/main/.github/workflows/scala-steward.yml) or any other kind of setting?

**Comment by alejandrohdezma** [comment]
Hey @mdedetrich, this is explained under [Guides](https://github.com/scala-steward-org/scala-steward-action/blob/master/README.md#guides) > **Updating a specific repository**. When using the action with a GitHub App, by default the action tries to update every repository where the app is installed. In your case, if you just want to use the application to authenticate, you need to add `github-app-auth-only: "true"`.

**Comment by mdedetrich** [comment]
@alejandrohdezma Thanks for the reply! Currently applying the suggested changes and I will report back once I confirm that it works (or not)

**Comment by mdedetrich** [comment]
WIth an unrelated permission issue fixed I can confirm that its now working as intended, thanks for the help!
