### ISSUE TITLE
Avoid pushing scala updates for non LTS versions

### ISSUE THREAD

**Issue by etspaceman** [scala-steward-org/scala-steward#3302]
It would be very helpful if updates for the scala language were limited to the LTS versions unless otherwise configured. The Steward pushed out versions for 3.4 recently and this version is not intended for libraries.

**Comment by bpholt** [comment]
Related https://github.com/scala-steward-org/scala-steward/issues/2467

**Comment by SethTisue** [comment]
(now that I'm back on my computer I see that) It's possible this was already fixed, as at modules/core/src/main/resources/default.scala-steward.conf I see

```
  // Ignore the next Scala 3 version until it is announced.
  { groupId = "org.scala-lang", artifactId = "scala3-compiler",     version = { exact = "3.4.0" } },
  { groupId = "org.scala-lang", artifactId = "scala3-library",      version = { exact = "3.4.0" } },
  { groupId = "org.scala-lang", artifactId = "scala3-library_sjs1", version = { exact = "3.4.0" } },
```

@Kordyjan but of course this is specific to 3.4.0; is there some update to the Scala 3 release steps that is still needed to prevent this from reoccurring...?

**Comment by Kordyjan** [comment]
For now, 3.4 releases are ignored. It will remain that way for some time. Later, we will propose a change to the Scala steward to only bump the version to the Scala Next version if the project is already on Scala Next.

**Comment by valencik** [comment]
@Kordyjan 
> For now, 3.4 releases are ignored.

It looks like updates are still going out: https://github.com/typelevel/typelevel.g8/pull/135

**Comment by mpilquist** [comment]
Another example: https://github.com/Comcast/ip4s/pull/575

**Comment by mzuehlke** [comment]
#3323 should fix that
