### ISSUE TITLE
Update Scala version in `.sdkmanrc`

### ISSUE THREAD

**Issue by achinaou** [scala-steward-org/scala-steward#3414]
It would be nice if Scala Steward could update the Scala version in the `.sdkmanrc` as the SDKMAN became one of the official ways to install Scala.

**Comment by mzuehlke** [comment]
When adding `.sdkmarc` to `updates.fileExtensions` in the `.scala-steward.conf` (See https://github.com/scala-steward-org/scala-steward/blob/main/docs/repo-specific-configuration.md) the Scala version should be updated.

**Comment by achinaou** [comment]
Yes, it did!

Would it be a good idea to include it in the default list?

**Comment by mzuehlke** [comment]
Sounds like a good idea 👍 . Feel free to provided a PR.
