### ISSUE TITLE
Wrong update of scala-library from 2.12 to 2.13

### ISSUE THREAD

**Issue by adpi2** [scala-steward-org/scala-steward#3424]
In https://github.com/scala/scala3.g8/pull/150 and other projects, Scala Steward tries to update the Scala library version from 2.12.20 to 2.13.15

Maybe @SethTisue knows more about this?

**Comment by adpi2** [comment]
Actually this is not new, it happened many times before: https://github.com/scala/scala3.g8/pull/141, https://github.com/scala/scala3.g8/pull/137, etc

**Comment by mzuehlke** [comment]
If you don't pin the Scala version to 2.12 it will with every newly released version try to update to `2.13.newest`.
You could add a `.scala-steward.conf` file, like this: https://github.com/scala-steward-org/sbt-plugin/pull/18

**Comment by mzuehlke** [comment]
And just to want to make you aware, if Scala Steward should  update the versions in the Template itself take a look at this FAQ entry: https://github.com/scala-steward-org/scala-steward/blob/main/docs/faq.md#can-scala-steward-update-dependencies-in-giter8-templates-
