### ISSUE TITLE
Closing pull-requests for retracted versions

### ISSUE THREAD

**Issue by mzuehlke** [scala-steward-org/scala-steward#3445]
It happens to the best developers that they release a a new version premature. Scala 3.6.0 was just the last example. 
The https://github.com/scala-steward-org/scala-steward/blob/main/modules/core/src/main/resources/default.scala-steward.conf lists multiple blocked artifacts.

The idea is to close pull requests of artifacts that get listed in `updates.retracted` and/or leave at lest a comment that this version shouldn't be used. The affected should be stored in the `PullRequestRepository`.

@scala-steward-org/core @WojciechMazur @SethTisue @Kordyjan

**Comment by fthomas** [comment]
Great idea! The entries in `updates.retracted` could contain an optional reason why a version was retracted and/or an URL that contains further information.
