### ISSUE TITLE
java.lang.IllegalArgumentException: GitHub app configuration is missing

### ISSUE THREAD

**Issue by nikita-ty754** [scala-steward-org/scala-steward#3480]
Hi
I started facing this issue after GitHub Enterprise support was added:
java.lang.IllegalArgumentException: GitHub app configuration is missing
I don’t use GitHub Enterprise, but this change has broken my existing CI setup. Is there any way to fix this?

Thanks!

**Comment by nikita-ty754** [comment]
[error] java.lang.IllegalArgumentException: GitHub app configuration is missing
[error]   at org.scalasteward.core.forge.ForgeAuthAlg$.$anonfun$create$1(ForgeAuthAlg.scala:59)
[error]   at scala.Option.getOrElse(Option.scala:201)
[error]   at org.scalasteward.core.forge.ForgeAuthAlg$.create(ForgeAuthAlg.scala:59)
[error]   at org.scalasteward.core.application.Context$.step1(Context.scala:132)
[error]   at org.scalasteward.core.application.Context$.$anonfun$step0$10(Context.scala:117)
[error]   at delay @ org.scalasteward.core.client.ClientConfiguration$.$anonfun$defaultHttpClient$1(ClientConfiguration.scala:47)
[error]   at executor @ org.scalasteward.core.client.ClientConfiguration$.defaultHttpClient(ClientConfiguration.scala:46)
[error]   at flatMap @ org.scalasteward.core.client.ClientConfiguration$.defaultHttpClient(ClientConfiguration.scala:46)
[error]   at map @ org.scalasteward.core.client.ClientConfiguration$.build(ClientConfiguration.scala:41)
[error]   at use @ org.scalasteward.core.Main$.run(Main.scala:27)
[error]   at delay @ org.scalasteward.core.client.ClientConfiguration$.$anonfun$defaultHttpClient$1(ClientConfiguration.scala:47)
[error]   at executor @ org.scalasteward.core.client.ClientConfiguration$.defaultHttpClient(ClientConfiguration.scala:46)
[error]   at flatMap @ org.scalasteward.core.client.ClientConfiguration$.defaultHttpClient(ClientConfiguration.scala:46)
[error]   at map @ org.scalasteward.core.client.ClientConfiguration$.build(ClientConfiguration.scala:41)
[error]   at use @ org.scalasteward.core.Main$.run(Main.scala:27)
[error]   at use @ org.scalasteward.core.Main$.run(Main.scala:27)
[error]   at delay @ org.scalasteward.core.application.Context$.$anonfun$step0$3(Context.scala:93)
[error]   at use @ org.scalasteward.core.Main$.run(Main.scala:27)

These are all flags i use when launching: 
--disable-sandbox 
--do-not-fork 
--workspace 
--repos-file 
--git-ask-pass 
--git-author-email 
--forge-api-host 
--forge-login  
--git-author-name

**Comment by nikita-ty754** [comment]
Am i right in thinking that after [(https://github.com/scala-steward-org/scala-steward/pull/3456)] the only viable option is to authenticate using this approach [https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/authenticating-as-a-github-app] ?

**Comment by mzuehlke** [comment]
That at least was not the intention of that PR.
Github App authentication for Github Enterprise should have been an additional way for authentication. Will need to take a closer look at that PR.

/cc @joan38

**Comment by joan38** [comment]
Looking 👀

**Comment by mzuehlke** [comment]
Fixed by #3481

**Comment by mzuehlke** [comment]
@nikita-ty754  please let me know if it work now for you.
