### ISSUE TITLE
Ability to club dependencyUpdates of a groupId in a single PR

### ISSUE THREAD

**Issue by anilkumarmyla** [scala-steward-org/scala-steward#412]
In its current form, if we have an sbt project with n artifacts with the same groupId but different version, scala-steward raises n PRs for each upgrade. 
```
io.group % package1 % version1
io.group % package2 % version2
..
..
io.group % packageN % versionN
```

Is it possible to club same group's upgrades into a single PR? I know this is the not the expected behavior since each indivudal unit should be tested separately

**Comment by Daenyth** [comment]
What happens if you have
```
val groupVersion = "1.0"
io.group % package1 % groupVersion
io.group % package2 % groupVersion
```

**Comment by fthomas** [comment]
My feeling is that it is probably hard to get right for a bot to include updates of multiple artifacts with different release cycles and different version numbers in one PR. Just the fact that the number of possible artifacts included in such a PR could vary over time seems problematic to me.

**Comment by anilkumarmyla** [comment]
Feel free to close this given the rationale in https://github.com/fthomas/scala-steward/issues/413#issuecomment-585526671
