### ISSUE TITLE
Update PR instead of creating a new one

### ISSUE THREAD

**Issue by anilkumarmyla** [scala-steward-org/scala-steward#418]
A library upgrading from version n to n+1, n+2 ... n+k ends up creating 'k' PRs and when the k'th PR is merged, all n+1...n+(k-1) PRs become obselete. To avoid this, we can keep updating existing PR with version increments. This may be similar to #119

**Comment by fthomas** [comment]
This could be useful for dependencies which often release a new version.

**Comment by manuzhang** [comment]
@fthomas I'd like to work on this feature. Is there a good way to test ?

**Comment by Daenyth** [comment]
I'd request that subsequent updates be additional commits; this is especially useful with scalafix.

Having separate commits per version will make `git bisect` easier for example in case of breakages, especially with #604 

example:

> - Upgrade foo from 1.2.2 to 1.2.3
> - Upgrade foo from 1.2.3 to 1.3.0
> - Run scalafix for foo 1.2.3->1.3.0

**Comment by fthomas** [comment]
@manuzhang The best way to test this is by running scala-steward yourself with a test repo. The unit tests are insufficient for testing the interaction with GitHub.

I like @Daenyth's suggestion.

**Comment by manuzhang** [comment]
@fthomas Sure.  Have you ever seen the following error in test ?

```
org.http4s.client.UnexpectedStatus: unexpected HTTP status: 401 Unauthorized
```

**Comment by fthomas** [comment]
@manuzhang That sounds like bad GitHub credentials. You might get more infos if you set the log-level to DEBUG in [logback.xml](https://github.com/fthomas/scala-steward/blob/master/modules/core/src/main/resources/logback.xml).

**Comment by manuzhang** [comment]
@fthomas Thanks. I forgot I had two-factor auth enabled for GitHub. Another question is whether `firejail` is required for the test. It seems Linux only.

**Comment by fthomas** [comment]
It is safe to disable firejail for testing.

**Comment by tyrcho** [comment]
has anyone already an idea on how to implement that ? it would be quite useful in my company, for instance we had 5 tapir updates in the past month on all our projects.

I'd be happy to implement and/or test this feature, maybe with some pointers from @fthomas about the implementation.

**Comment by Daenyth** [comment]
Is there a part of the current architecture that makes the logic hard?

I would (naively) think that it would go something like:
- See available update for foolib
- Scan open PRs for author==me that update foolib (maybe library name in the branch name?)
- update PR if found, otherwise create PR

**Comment by fthomas** [comment]
Closing of obsolete PRs (#119) has now been implemented. I prefer that solution over updating already existing PRs because that is/was much easier to implement and is also conceptually easier. To keep maintenance costs manageable, I'm now :-1: on adding the feature described here.
