### ISSUE TITLE
Mdoc for creating good/bad examples documentation

### ISSUE THREAD

**Issue by kiranbayram** [scala-steward-org/scala-steward#461]
Try out https://scalameta.org/mdoc/ for creating good/bad examples documentation(markdown file) from output of ExampleTest.scala.

**Comment by kiranbayram** [comment]
Just looked into mdoc but i don't see how exactly one can use it to create markdown file from output of a test :frowning_face:

**Comment by fthomas** [comment]
If we were using mdoc we would only have a markdown source file which generates machine-checked documentation and there would be no need to have a separate test.

**Comment by fthomas** [comment]
I think these examples are less needed once #2816 lands in main. I'm therefore closing this issue.
