### ISSUE TITLE
Support assignment or review requests via configuration

### ISSUE THREAD

**Issue by travisbrown** [scala-steward-org/scala-steward#504]
It would be convenient to be able to handle scala-steward's PRs through the standard tabs in GitHub's [pull requests interface](https://github.com/pulls), and I was wondering whether other people would be interested in having this supported via configuration options in `.scala-steward.conf`. You'd add something like `assignees = ["travisbrown"]` and all update pull requests would be assigned to that person.

(I know this could also be done via `CODEOWNERS`, but that doesn't seem to be a perfect fit––e.g. I might want to be responsible for tending scala-steward updates on a repo where I'm not a primary maintainer or owner. Maybe that's a stretch, though.)

**Comment by fthomas** [comment]
I like the idea, but I think @scala-steward lacks permissions to assign PRs. If I'm not mistaken you need to have write access to a repository to assign issues and PRs.

If scala-steward would be a GitHub App (which I'm also working on) it would have appropriate access and could support this. In the meantime I think you can accomplish the same with [Mergify.io](https://mergify.io/).

**Comment by philipphoffmann** [comment]
Would this be feasible with the GitLab integration?

**Comment by fthomas** [comment]
@philipphoffmann I've no idea if GitLab also requires special permissions for assigning merge requests.

**Comment by fthomas** [comment]
Since I mentioned Mergify before: this repo's [`mergify.yml`](https://github.com/fthomas/scala-steward/blob/33d4d2d6bd6f3788fb74e70618a7be25457758c9/.mergify.yml) shows now how @scala-steward's PRs can be assigned automatically.
