### ISSUE TITLE
Support monorepos with scala subfolders

### ISSUE THREAD

**Issue by pvillega** [scala-steward-org/scala-steward#678]
We currently have a project in which the scala project is located in a subfolder in the repo. Currently Steward can't identify that project as a Scala project, and it ignores it.

We would need a way to indicate a subfolder in a git repository where the scala project is located.

We are aware that there is a closed issue regarding projects following the Play/Akka structure, but this is a different issue.

**Comment by exoego** [comment]
Similar to https://github.com/fthomas/scala-steward/issues/46

**Comment by pvillega** [comment]
Yes, but not exactly the same as #46 if I understand correctly. #46 seems to be focussed on Play projects (based on examples), this is more 'any subfolder that can be a full project by itself'. Then again I may be misreading :)

**Comment by exoego** [comment]
Yes, I mean this issue seems to supersede #46, since this seems able to cover #46

**Comment by exoego** [comment]
I am working on this.

**Comment by ashawley** [comment]
Will this also make it possible to support repos that contain [Giter8](http://www.foundweekends.org/giter8/) templates?

Here's an example: https://github.com/scala/scala-seed.g8

**Comment by ashawley** [comment]
> Will this also make it possible to support repos that contain [Giter8](http://www.foundweekends.org/giter8/) templates?

I saw that Scala Steward is at least updating the sbt version of a g8 tempmlate, see https://github.com/scala/scalatest-example.g8/pull/14

**Comment by kluen** [comment]
Hi @exoego, just curious, is this still being worked on?

**Comment by exoego** [comment]
No, I am no longer working on this feature (I closed my WIP PR #721).
Anyone can take over the PR.

FYI, #1093 is another approach for this feature.

**Comment by kluen** [comment]
Thanks for the info, I haven't found those PRs :)
