### ISSUE TITLE
document integration with gitlab

### ISSUE THREAD

**Issue by tyrcho** [scala-steward-org/scala-steward#745]
The integration with Gitlab is not very difficult but newcomers could struggle.

I made a public, minimalist repository in which it work pretty well:
https://gitlab.com/colisweb-open-source/scala-steward/

I configured a scheduled pipeline so the CI job is triggered by Gitlab CI everyday.

I'd be happy to help with the writing of this documentation.

**Comment by robstoll** [comment]
I setup scala-steward for gitlab as well and could chip in with troubleshooting tips

**Comment by fthomas** [comment]
Fixed by #1633.
