### ISSUE TITLE
Use HTTP client that support proxy settings

### ISSUE THREAD

**Issue by fthomas** [scala-steward-org/scala-steward#888]
I'm currently experiencing a problem with Scala Steward behind a corporate web proxy. It tries to create a PR and fails with a `java.net.ConnectException: Connection refused` when it tries to check if the URL for the version diff exists via the `HttpExistenceClient`. Using standard [Java options for proxy settings](https://docs.oracle.com/javase/8/docs/technotes/guides/net/proxies.html) have no effect and I believe this due https://github.com/http4s/http4s/issues/251. So instead of using http4s-blaze-client, I think we should switch to a http4s-client that supports the Java proxy settings.

**Comment by ChristopherDavenport** [comment]
async-http-client is probably the fastest path, ember is experimental but the easiest to fix. http4s-jdk-client is also really nice but new as well.

**Comment by fthomas** [comment]
Replacing http4s-blaze-client with http4s-async-http-client was a breeze, thanks @ChristopherDavenport for the suggestion.

**Comment by fthomas** [comment]
Using http4s-async-http-client actually never fixed this issue for me, so I'm reopening this again.

I've now tried the following clients:
* http4s-blaze-client 0.20.10
* http4s-async-http-client 0.21.8
* http4s-ember-client 0.21.8
* http4s-okhttp-client 0.21.8

The only client that picked up the `http{,s}.proxy{Host,Port}` properties in their default configuration and worked for me is the http4s-okhttp-client. I'll therefore create a PR replacing http4s-async-http-client with http4s-okhttp-client.
