### ISSUE TITLE
Wrong dependency gets updated

### ISSUE THREAD

**Issue by psttf** [scala-steward-org/scala-steward#960]
I've noticed the following unexpected behavior: if there are two dependencies in build.sbt with the same version number and one of them is marked as ignored Steward updates the wrong dependency.

Minimal sample project: https://gitlab.com/psttf/scala-steward-issue

It has dependencies to Bootstrap and jQuery webjars with the same version number. Bootstrap is marked as ignored via comment. Still, Steward tries to update Bootstrap and updates jQuery instead and duplicates jQuery dependency. In my other (non-minimal) project with the same problem duplication does not occur.

PR created by Steward: https://gitlab.com/psttf/scala-steward-issue/merge_requests/1

The PR is named "Update bootstrap to 4.3.1" but it updates jQuery instead!

I use Docker Hub image fthomas/scala-steward:latest to run scala-steward, image sha256:fdc23a0f2d89b299be4f8f865cb274ba2e64730d355c4cfb7793b55da0906344

**Comment by psttf** [comment]
Thank you for fixing this!

**Comment by fthomas** [comment]
It was about time! :-)
